In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
pip install pyreadstat

Collecting pyreadstat
  Downloading pyreadstat-1.2.8-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.0 kB)
Requirement already satisfied: pandas>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from pyreadstat) (2.2.2)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.2.0->pyreadstat) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.2.0->pyreadstat) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.2.0->pyreadstat) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.2.0->pyreadstat) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas>=1.2.0->pyreadstat) (1.17.0)
Downloading pyreadstat-1.2.8-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 21.3 MB/s eta 0:00:00
Installing collected packages: pyreadstat
Successfully installed pyreadstat-1.2.8

In [ ]:
#Household members dataset
path = '/content/drive/MyDrive/MICS6/Round/Nigeria MICS6 Datasets/hl.sav'
df_hl = pd.read_spss(path)

In [ ]:
#Household members dataset
path = '/content/drive/MyDrive/MICS6/Round/Nigeria MICS6 Datasets/fs.sav'
df_fs = pd.read_spss(path)

In [ ]:
#extracting function
def extract_columns_from_dataframes(dataframes, columns):
    """
    Extract specified columns from a list of DataFrames.

    Parameters:
    - dataframes: List of DataFrames to extract columns from.
    - columns: List of column names to extract.

    Returns:
    - A new DataFrame containing the extracted columns from all DataFrames.
    """
    extracted_dataframes = []  # List to hold the extracted DataFrames

    for df in dataframes:
        # Extract the specified columns, ensuring they exist in the DataFrame
        extracted_df = df[columns].copy() if all(col in df.columns for col in columns) else pd.DataFrame()

        # Append the extracted DataFrame to the list
        extracted_dataframes.append(extracted_df)

    # Concatenate all extracted DataFrames into one
    combined_extracted_df = pd.concat(extracted_dataframes, ignore_index=True)

    return combined_extracted_df

In [ ]:
# List of DataFrames to extract from
dataframes = [df_hl]

# Columns to extract
columns_to_extract = ['HH1', 'HH2', 'HL1', 'HL12', 'HL13', 'HL14', 'HL15', 'HL16', 'HL17', 'HL18', 'HL19']

# Call the function
extracted_data = extract_columns_from_dataframes(dataframes, columns_to_extract)

# Display the result
print(extracted_data)

           HH1   HH2  HL1 HL12 HL13 HL14 HL15 HL16 HL17 HL18 HL19
0          1.0   1.0  1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1          1.0   1.0  2.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2          1.0   1.0  3.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3          1.0   1.0  4.0  YES  YES  1.0  NaN   NO  NaN  NaN  NaN
4          1.0   2.0  1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
...        ...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
207491  2187.0  19.0  4.0  YES  YES  2.0  NaN  YES  YES  1.0  NaN
207492  2187.0  20.0  1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
207493  2187.0  20.0  2.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
207494  2187.0  20.0  3.0  YES  YES  2.0  NaN  YES  YES  1.0  NaN
207495  2187.0  20.0  4.0  YES  YES  2.0  NaN  YES  YES  1.0  NaN

[207496 rows x 11 columns]

In [ ]:
list(df_fs.columns)

['HH1',
 'HH2',
 'LN',
 'FS1',
 'FS2',
 'FS3',
 'FSINT',
 'FS4',
 'FS5',
 'FS6',
 'FS7D',
 'FS7M',
 'FS7Y',
 'FS9',
 'FS10',
 'FS17',
 'FS8H',
 'FS8M',
 'FS11H',
 'FS11M',
 'FS12',
 'FS13',
 'FS14',
 'FS15',
 'FSHINT',
 'FS15A',
 'FS15B',
 'FS15C',
 'FS15D',
 'FSFIN',
 'CB2M',
 'CB2Y',
 'CB3',
 'CB4',
 'CB5A',
 'CB5B',
 'CB6',
 'CB7',
 'CB8A',
 'CB8B',
 'CB9',
 'CB10A',
 'CB10B',
 'CB11',
 'CB12A',
 'CB12B',
 'CB12C',
 'CB12D',
 'CB12X',
 'CB12NR',
 'BRS1',
 'BRS2',
 'BRS3',
 'CL1A',
 'CL1B',
 'CL1C',
 'CL1X',
 'CL3',
 'CL4',
 'CL5',
 'CL6A',
 'CL6B',
 'CL6C',
 'CL6D',
 'CL6E',
 'CL6X',
 'CL7',
 'CL8',
 'CL9',
 'CL10',
 'CL11A',
 'CL11B',
 'CL11C',
 'CL11D',
 'CL11E',
 'CL11F',
 'CL11X',
 'CL13',
 'FCD2A',
 'FCD2B',
 'FCD2C',
 'FCD2D',
 'FCD2E',
 'FCD2F',
 'FCD2G',
 'FCD2H',
 'FCD2I',
 'FCD2J',
 'FCD2K',
 'FCD3',
 'FCD4',
 'FCD5',
 'FCF1',
 'FCF2',
 'FCF3',
 'FCF6',
 'FCF8',
 'FCF10',
 'FCF11',
 'FCF12',
 'FCF13',
 'FCF14',
 'FCF15',
 'FCF16',
 'FCF17',
 'FCF18',
 'FCF19',
 'FCF20',
 'FCF21',
 'FCF22',
 'FCF23',
 'FCF24',
 'FCF25',
 'FCF26',
 'PR3',
 'PR5',
 'PR6',
 'PR7',
 'PR8',
 'PR9A',
 'PR9B',
 'PR10',
 'PR11A',
 'PR11B',
 'PR12A',
 'PR12B',
 'PR12C',
 'PR12D',
 'PR12X',
 'PR13',
 'PR15',
 'FL1',
 'FL2H',
 'FL2M',
 'FL3',
 'FL4A',
 'FL4B',
 'FL4C',
 'FL4NR',
 'FL6A',
 'FL6B',
 'FL7',
 'FL9',
 'FL10',
 'FL10C',
 'FL13',
 'FL14',
 'FL15',
 'FL16',
 'FL17',
 'FL18',
 'FLINTRO',
 'FL19W1',
 'FL19W2',
 'FL19W3',
 'FL19W4',
 'FL19W5',
 'FL19W6',
 'FL19W7',
 'FL19W8',
 'FL19W9',
 'FL19W10',
 'FL19W11',
 'FL19W12',
 'FL19W13',
 'FL19W14',
 'FL19W15',
 'FL19W16',
 'FL19W17',
 'FL19W18',
 'FL19W19',
 'FL19W20',
 'FL19W21',
 'FL19W22',
 'FL19W23',
 'FL19W24',
 'FL19W25',
 'FL19W26',
 'FL19W27',
 'FL19W28',
 'FL19W29',
 'FL19W30',
 'FL19W31',
 'FL19W32',
 'FL19W33',
 'FL19W34',
 'FL19W35',
 'FL19W36',
 'FL19W37',
 'FL19W38',
 'FL19W39',
 'FL19W40',
 'FL19W41',
 'FL19W42',
 'FL19W43',
 'FL19W44',
 'FL19W45',
 'FL19W46',
 'FL19W47',
 'FL19W48',
 'FL19W49',
 'FL19W50',
 'FL19W51',
 'FL19W52',
 'FL19W53',
 'FL19W54',
 'FL19W55',
 'FL19W56',
 'FL19W57',
 'FL19W58',
 'FL19W59',
 'FL19W60',
 'FL19W61',
 'FL19W62',
 'FL19W63',
 'FL19W64',
 'FL19W65',
 'FL19W66',
 'FL19W67',
 'FL19W68',
 'FL19W69',
 'FL19W70',
 'FL19W71',
 'FL19W72',
 'FL19W73',
 'FL19W74',
 'FL19W75',
 'FL19W76',
 'FL19W77',
 'FL19W78',
 'FL19W79',
 'FL19W80',
 'FL19W81',
 'FL19W82',
 'FL19W83',
 'FL19W84',
 'FL19W85',
 'FL19W86',
 'FL19W87',
 'FL19W88',
 'FL20A',
 'FL20B',
 'FL21BA',
 'FL21BB',
 'FL21BC',
 'FL21BD',
 'FL21BE',
 'FL21D',
 'FL21G',
 'FL21H',
 'FL21I',
 'FL21J',
 'FL21K',
 'FL21L',
 'FL21MN',
 'FL21O',
 'FL21OW1',
 'FL21OW2',
 'FL21OW3',
 'FL21OW4',
 'FL21OW5',
 'FL21OW6',
 'FL21OW7',
 'FL21OW8',
 'FL21OW9',
 'FL21OW10',
 'FL21OW11',
 'FL21OW12',
 'FL21OW13',
 'FL21OW14',
 'FL21OW15',
 'FL21OW16',
 'FL21OW17',
 'FL21OW18',
 'FL21OW19',
 'FL21OW20',
 'FL21OW21',
 'FL21OW22',
 'FL21OW23',
 'FL21OW24',
 'FL21OW25',
 'FL21OW26',
 'FL21OW27',
 'FL21OW28',
 'FL21OW29',
 'FL21OW30',
 'FL21OW31',
 'FL21OW32',
 'FL21OW33',
 'FL21OW34',
 'FL21OW35',
 'FL21OW36',
 'FL21OW37',
 'FL21OW38',
 'FL21OW39',
 'FL21OW40',
 'FL21OW41',
 'FL21OW42',
 'FL21OW43',
 'FL21OW44',
 'FL21OW45',
 'FL21OW46',
 'FL21OW47',
 'FL21OW48',
 'FL21OW49',
 'FL21OW50',
 'FL21OW51',
 'FL21OW52',
 'FL21OW53',
 'FL21OW54',
 'FL21OW55',
 'FL21OW56',
 'FL21OW57',
 'FL21OW58',
 'FL21OW59',
 'FL21OW60',
 'FL21OW61',
 'FL21OW62',
 'FL21OW63',
 'FL21PA',
 'FL21PB',
 'FL22A',
 'FL22B',
 'FL22C',
 'FL22D',
 'FL22E',
 'FL23A',
 'FL23B',
 'FL23C',
 'FL23D',
 'FL23E',
 'FL23F',
 'FL24A',
 'FL24B',
 'FL24C',
 'FL24D',
 'FL24E',
 'FL25A',
 'FL25B',
 'FL25C',
 'FL25D',
 'FL25E',
 'FL26',
 'FL26A',
 'FL26B',
 'FL26C',
 'FL26D',
 'FL26E',
 'FL27A',
 'FL27B',
 'FL27C',
 'FL27D',
 'FL27E',
 'FL27AA',
 'FL28',
 'FS15F0$1',
 'FS15F0$2',
 'FS15F0$3',
 'FS15G$1',
 'FS15G$2',
 'FS15G$3',
 'FS15H$1',
 'FS15H$2',
 'FS15H$3',
 'FS15IA$1',
 'FS15IA$2',
 'FS15IA$3',
 'FS15IB$1',
 'FS15IB$2',
 'FS15IB$3',
 'FS15IC$1',
 'FS15IC$2',
 'FS15IC$3',
 'FS15ID$1',
 'FS15ID$2',
 'FS15ID$3',
 'FS15IE$1',
 'FS15IE$2',
 'FS15IE$3',
 'FS15IF$1',
 'FS15IF$2',
 'FS15IF$3',
 'FS15IG$1',
 'FS15IG$2',
 'FS15IG$3',
 'FS15IH$1',
 'FS15IH$2',
 'FS15IH$3',
 'FS15IX$1',
 'FS15IX$2',
 'FS15IX$3',
 'FS15J$1',
 'FS15J$2',
 'FS15J$3',
 'HH4',
 'HH6',
 'HH7',
 'HH52',
 'HL4',
 'ED5A',
 'ED5B',
 'FSAGE',
 'FSDOI',
 'FSDOB',
 'lang1',
 'lang2',
 'survey',
 'zone',
 'melevel',
 'fselevel',
 'schage',
 'fsinsurance',
 'fsdisability',
 'ethnicity',
 'fshweight',
 'fsweight',
 'PSU',
 'stratum',
 'wscore',
 'windex5',
 'windex10',
 'wscoreu',
 'windex5u',
 'windex10u',
 'wscorer',
 'windex5r',
 'windex10r']

In [ ]:
# List of DataFrames to extract from
dataframes = [df_fs]

# Columns to extract
columns_to_extract = ['HH1', 'HH2', 'LN', 'CL1A', 'CL1B', 'CL1C', 'CL1X', 'CL3', 'CL4', 'CL5', 'CL6A', 'CL6B', 'CL6C', 'CL6D', 'CL6E', 'CL6X',
                      'CL7', 'CL8', 'CL9', 'CL10', 'CL11A', 'CL11B', 'CL11C', 'CL11D', 'CL11E', 'CL11F', 'CL11X', 'CL13', 'CB3', 'HH6', 'HL4', 'ED5A', 'ED5B', 'melevel', 'fselevel',
                      'fsinsurance', 'fsdisability', 'fshweight', 'fsweight', 'ethnicity', 'HH7', 'zone']

# Call the function
extracted_data_fs = extract_columns_from_dataframes(dataframes, columns_to_extract)

# Display the result
print(extracted_data_fs)

          HH1   HH2    LN CL1A CL1B CL1C CL1X  CL3  CL4  CL5 CL6A CL6B CL6C CL6D CL6E CL6X  CL7   CL8  CL9 CL10 CL11A CL11B CL11C CL11D CL11E CL11F CL11X CL13   CB3    HH6     HL4              ED5A     ED5B           melevel          fselevel        fsinsurance                  fsdisability  fshweight  fsweight        ethnicity   HH7           zone
0         1.0   1.0   4.0   NO  YES  YES  YES  4.0   NO   NO  YES   NO   NO   NO   NO   NO   NO   NaN   NO  NaN    NO    NO   YES   YES    NO    NO    NO  3.0  10.0  URBAN    MALE           PRIMARY  GRADE 3           Primary  Junior secondary  Without insurance     Has functional difficulty   0.631502  0.631502             Igbo  ABIA     South East
1         1.0   2.0   2.0   NO   NO   NO   NO  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  YES   2.0   NO  NaN   YES   YES   YES   YES    NO    NO   YES  4.0  16.0  URBAN  FEMALE  SENIOR SECONDARY  GRADE 3  Senior secondary  Senior secondary  Without insurance  Has no functional difficulty   0.631502  0.631502             Igbo  ABIA     South East
2         1.0   3.0   3.0   NO   NO   NO   NO  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NO   NaN   NO  NaN    NO    NO   YES    NO    NO    NO    NO  0.0   5.0  URBAN    MALE   HIGHER/TERTIARY  GRADE 4   Higher/tertiary              None  Without insurance     Has functional difficulty   0.631502  0.631502             Igbo  ABIA     South East
3         1.0   5.0   5.0   NO  YES   NO   NO  3.0   NO   NO   NO   NO   NO   NO   NO   NO  YES  10.0   NO  NaN    NO   YES   YES   YES    NO    NO   YES  5.0  16.0  URBAN    MALE  SENIOR SECONDARY  GRADE 3  Senior secondary  Senior secondary  Without insurance  Has no functional difficulty   0.631502  0.631502             Igbo  ABIA     South East
4         1.0   6.0   5.0   NO  YES   NO  YES  8.0   NO   NO  YES  YES   NO   NO   NO  YES  YES   2.0  YES  0.0   YES   YES   YES   YES    NO    NO   YES  4.0  15.0  URBAN  FEMALE  SENIOR SECONDARY  GRADE 3  Senior secondary  Junior secondary  Without insurance  Has no functional difficulty   0.631502  0.631502             Igbo  ABIA     South East
...       ...   ...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...  ...  ...   ...   ...   ...   ...   ...   ...   ...  ...   ...    ...     ...               ...      ...               ...               ...                ...                           ...        ...       ...              ...   ...            ...
22701  1850.0  13.0   5.0   NO   NO   NO   NO  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NO   NaN   NO  NaN    NO    NO    NO    NO    NO    NO    NO  NaN   7.0  RURAL    MALE  SENIOR SECONDARY  GRADE 3  Senior secondary           Primary  Without insurance  Has no functional difficulty   0.346335  0.346335  Other ethnicity   FCT  North Central
22702  1850.0  15.0   3.0   NO   NO   NO   NO  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NO   NaN   NO  NaN    NO    NO    NO    NO    NO    NO    NO  NaN   5.0  RURAL    MALE               NaN      NaN              None           Primary  Without insurance  Has no functional difficulty   0.346335  0.346335  Other ethnicity   FCT  North Central
22703  1850.0  17.0  10.0   NO   NO   NO   NO  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NO   NaN   NO  NaN    NO    NO    NO    NO    NO    NO    NO  NaN   6.0  RURAL    MALE  JUNIOR SECONDARY  GRADE 3  Junior secondary           Primary  Without insurance     Has functional difficulty   0.346335  1.731675  Other ethnicity   FCT  North Central
22704  1850.0  19.0   7.0   NO   NO   NO   NO  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  YES   6.0   NO  NaN    NO    NO   YES   YES    NO    NO    NO  5.0  17.0  RURAL    MALE               NaN      NaN              None  Junior secondary  Without insurance  Has no functional difficulty   0.346335  0.346335  Other ethnicity   FCT  North Central
22705  1850.0  20.0   7.0   NO   NO   NO   NO  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NO   NaN   NO  NaN    NO    NO    NO    NO    NO    NO    NO  NaN   6.0  RURAL    MALE  JUNIOR SECONDARY  GRADE 3  Junior secondary           Primary  Without insurance     Has functional difficulty   0.346335  1.385340  Other ethnicity   FCT  North Central

[22706 rows x 42 columns]

In [ ]:
# Renaming all variables
columns = ['Cluster number',
'Household number', 'Line number', 'Is natural mother alive', 'Does natural mother live in HH', 'Natural mother\'s line number in HH', 'Where does natural mother live',
           'Is natural father alive', 'Does natural father live in HH', 'Natural father\'s line number in HH', 'Where does natural father live']
extracted_data.columns = columns

In [ ]:
extracted_data.head(20)

    Cluster number  Household number  Line number Is natural mother alive Does natural mother live in HH Natural mother's line number in HH Where does natural mother live Is natural father alive Does natural father live in HH Natural father's line number in HH Where does natural father live
0              1.0               1.0          1.0                     NaN                            NaN                                NaN                            NaN                     NaN                            NaN                                NaN                            NaN
1              1.0               1.0          2.0                     NaN                            NaN                                NaN                            NaN                     NaN                            NaN                                NaN                            NaN
2              1.0               1.0          3.0                     NaN                            NaN                                NaN                            NaN                     NaN                            NaN                                NaN                            NaN
3              1.0               1.0          4.0                     YES                            YES                                1.0                            NaN                      NO                            NaN                                NaN                            NaN
4              1.0               2.0          1.0                     NaN                            NaN                                NaN                            NaN                     NaN                            NaN                                NaN                            NaN
5              1.0               2.0          2.0                     YES                             NO                                NaN                         ABROAD                      NO                            NaN                                NaN                            NaN
6              1.0               3.0          1.0                     NaN                            NaN                                NaN                            NaN                     NaN                            NaN                                NaN                            NaN
7              1.0               3.0          2.0                     NaN                            NaN                                NaN                            NaN                     NaN                            NaN                                NaN                            NaN
8              1.0               3.0          3.0                     YES                            YES                                2.0                            NaN                     YES                            YES                                1.0                            NaN
9              1.0               3.0          4.0                     YES                            YES                                2.0                            NaN                     YES                            YES                                1.0                            NaN
10             1.0               3.0          5.0                     YES                            YES                                2.0                            NaN                     YES                            YES                                1.0                            NaN
11             1.0               4.0          1.0                     NaN                            NaN                                NaN                            NaN                     NaN                            NaN                                NaN                            NaN
12             1.0               4.0          2.0                     NaN                            NaN                                NaN                            NaN                     NaN                            NaN                                NaN                            NaN
13             1.0               4.0          3.0                     NaN                            NaN                                NaN                            NaN                     NaN                            NaN                                NaN                            NaN
14             1.0               4.0          4.0                     NaN                            NaN                                NaN                            NaN                     NaN                            NaN                                NaN                            NaN
15             1.0               5.0          1.0                     NaN                            NaN                                NaN                            NaN                     NaN                            NaN                                NaN                            NaN
16             1.0               5.0          2.0                     NaN                            NaN                                NaN                            NaN                     NaN                            NaN                                NaN                            NaN
17             1.0               5.0          3.0                     NaN                            NaN                                NaN                            NaN                     NaN                            NaN                                NaN                            NaN
18             1.0               5.0          4.0                     NaN                            NaN                                NaN                            NaN                     NaN                            NaN                                NaN                            NaN
19             1.0               5.0          5.0                     YES                            YES                                2.0                            NaN                     YES                            YES                                1.0                            NaN

In [ ]:
extracted_data_fs.head()

   HH1  HH2   LN CL1A CL1B CL1C CL1X  CL3  CL4  CL5 CL6A CL6B CL6C CL6D CL6E CL6X  CL7   CL8  CL9 CL10 CL11A CL11B CL11C CL11D CL11E CL11F CL11X CL13   CB3    HH6     HL4              ED5A     ED5B           melevel          fselevel        fsinsurance                  fsdisability  fshweight  fsweight ethnicity   HH7        zone
0  1.0  1.0  4.0   NO  YES  YES  YES  4.0   NO   NO  YES   NO   NO   NO   NO   NO   NO   NaN   NO  NaN    NO    NO   YES   YES    NO    NO    NO  3.0  10.0  URBAN    MALE           PRIMARY  GRADE 3           Primary  Junior secondary  Without insurance     Has functional difficulty   0.631502  0.631502      Igbo  ABIA  South East
1  1.0  2.0  2.0   NO   NO   NO   NO  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  YES   2.0   NO  NaN   YES   YES   YES   YES    NO    NO   YES  4.0  16.0  URBAN  FEMALE  SENIOR SECONDARY  GRADE 3  Senior secondary  Senior secondary  Without insurance  Has no functional difficulty   0.631502  0.631502      Igbo  ABIA  South East
2  1.0  3.0  3.0   NO   NO   NO   NO  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NO   NaN   NO  NaN    NO    NO   YES    NO    NO    NO    NO  0.0   5.0  URBAN    MALE   HIGHER/TERTIARY  GRADE 4   Higher/tertiary              None  Without insurance     Has functional difficulty   0.631502  0.631502      Igbo  ABIA  South East
3  1.0  5.0  5.0   NO  YES   NO   NO  3.0   NO   NO   NO   NO   NO   NO   NO   NO  YES  10.0   NO  NaN    NO   YES   YES   YES    NO    NO   YES  5.0  16.0  URBAN    MALE  SENIOR SECONDARY  GRADE 3  Senior secondary  Senior secondary  Without insurance  Has no functional difficulty   0.631502  0.631502      Igbo  ABIA  South East
4  1.0  6.0  5.0   NO  YES   NO  YES  8.0   NO   NO  YES  YES   NO   NO   NO  YES  YES   2.0  YES  0.0   YES   YES   YES   YES    NO    NO   YES  4.0  15.0  URBAN  FEMALE  SENIOR SECONDARY  GRADE 3  Senior secondary  Junior secondary  Without insurance  Has no functional difficulty   0.631502  0.631502      Igbo  ABIA  South East

In [ ]:
# Renaming all variables
columns = ['Cluster number', 'Household number', 'Line number', 'Worked or helped on garden in past week', 'Helped in family business in past week', 'Produced or sold articles in past week', 'Engaged in any other activity for income in past week',
           'Hours worked in past week', 'Activities required carrying heavy loads', 'Activities required working with dangerous tools or heavy machinery', 'Description of work: exposed to dust, fumes or gas',
           'Description of work: exposed to extreme temperatures or humidity', 'Description of work: exposed to loud noise or vibration', 'Description of work: required to work at heights',
           'Description of work: required to work with chemicals', 'Description of work: exposed to other', 'Fetched water in past week', 'Hours spent fetching water in past week',
           'Collected firewood in past week', 'Hours spent collecting firewood in past week', 'Household chores in past week:shopping', 'Household chores in past week: cooking', 'Household chores in past week: washing dishes or cleaning around the house',
           'Household chores in past week: washing clothes', 'Household chores in past week: caring for children', 'Household chores in past week: caring for old or sick', 'Household chores in past week: other household tasks',
           'Number of hours engaged in past week', 'Age of child', 'HH6', 'HL4', 'ED5A', 'ED5B', 'melevel', 'fselevel', 'fsinsurance', 'fsdisability', 'fshweight', 'fsweight', 'ethnicity',
           'HH7', 'zone']
extracted_data_fs.columns = columns

In [ ]:
extracted_data_fs.head()

   Cluster number  Household number  Line number Worked or helped on garden in past week Helped in family business in past week Produced or sold articles in past week Engaged in any other activity for income in past week Hours worked in past week Activities required carrying heavy loads Activities required working with dangerous tools or heavy machinery Description of work: exposed to dust, fumes or gas Description of work: exposed to extreme temperatures or humidity Description of work: exposed to loud noise or vibration Description of work: required to work at heights Description of work: required to work with chemicals Description of work: exposed to other Fetched water in past week Hours spent fetching water in past week Collected firewood in past week Hours spent collecting firewood in past week Household chores in past week:shopping Household chores in past week: cooking Household chores in past week: washing dishes or cleaning around the house Household chores in past week: washing clothes Household chores in past week: caring for children Household chores in past week: caring for old or sick Household chores in past week: other household tasks Number of hours engaged in past week  Age of child    HH6     HL4              ED5A     ED5B           melevel          fselevel        fsinsurance                  fsdisability  fshweight  fsweight ethnicity   HH7        zone
0             1.0               1.0          4.0                                      NO                                    YES                                    YES                                                YES                          4.0                                       NO                                                 NO                                                                 YES                                                 NO                                                               NO                                                    NO                                                 NO                                      NO                         NO                                     NaN                              NO                                          NaN                                     NO                                     NO                                                YES                                                                    YES                                                 NO                                                 NO                                                    NO                                    3.0          10.0  URBAN    MALE           PRIMARY  GRADE 3           Primary  Junior secondary  Without insurance     Has functional difficulty   0.631502  0.631502      Igbo  ABIA  South East
1             1.0               2.0          2.0                                      NO                                     NO                                     NO                                                 NO                          NaN                                      NaN                                                NaN                                                                 NaN                                                NaN                                                              NaN                                                   NaN                                                NaN                                     NaN                        YES                                     2.0                              NO                                          NaN                                    YES                                    YES                                                YES                                                                    YES                                                 NO                                                 NO                                                   YES                                    4.0          16.0  URBAN  FEMALE  SENIOR SECONDARY  GRADE 3  Senior secondary  Senior secondary  Without insurance  Has no functional difficulty   0.631502  0.631502      Igbo  ABIA  South East
2             1.0               3.0          3.0                                      NO                                     NO                                     NO                                                 NO                          NaN                                      NaN                                                NaN                                                                 NaN                                                NaN                                                              NaN                                                   NaN                                                NaN                                     NaN                         NO                                     NaN                              NO                                          NaN                                     NO                                     NO                                                YES                                                                     NO                                                 NO                                                 NO                                                    NO                                    0.0           5.0  URBAN    MALE   HIGHER/TERTIARY  GRADE 4   Higher/tertiary              None  Without insurance     Has functional difficulty   0.631502  0.631502      Igbo  ABIA  South East
3             1.0               5.0          5.0                                      NO                                    YES                                     NO                                                 NO                          3.0                                       NO                                                 NO                                                                  NO                                                 NO                                                               NO                                                    NO                                                 NO                                      NO                        YES                                    10.0                              NO                                          NaN                                     NO                                    YES                                                YES                                                                    YES                                                 NO                                                 NO                                                   YES                                    5.0          16.0  URBAN    MALE  SENIOR SECONDARY  GRADE 3  Senior secondary  Senior secondary  Without insurance  Has no functional difficulty   0.631502  0.631502      Igbo  ABIA  South East
4             1.0               6.0          5.0                                      NO                                    YES                                     NO                                                YES                          8.0                                       NO                                                 NO                                                                 YES                                                YES                                                               NO                                                    NO                                                 NO                                     YES                        YES                                     2.0                             YES                                          0.0                                    YES                                    YES                                                YES                                                                    YES                                                 NO                                                 NO                                                   YES                                    4.0          15.0  URBAN  FEMALE  SENIOR SECONDARY  GRADE 3  Senior secondary  Junior secondary  Without insurance  Has no functional difficulty   0.631502  0.631502      Igbo  ABIA  South East

In [ ]:
#merging

merger = pd.merge(extracted_data, extracted_data_fs, how = 'inner', on = ['Cluster number', 'Household number', 'Line number'])

In [ ]:
merger.head()

   Cluster number  Household number  Line number Is natural mother alive Does natural mother live in HH Natural mother's line number in HH Where does natural mother live Is natural father alive Does natural father live in HH Natural father's line number in HH Where does natural father live Worked or helped on garden in past week Helped in family business in past week Produced or sold articles in past week Engaged in any other activity for income in past week Hours worked in past week Activities required carrying heavy loads Activities required working with dangerous tools or heavy machinery Description of work: exposed to dust, fumes or gas Description of work: exposed to extreme temperatures or humidity Description of work: exposed to loud noise or vibration Description of work: required to work at heights Description of work: required to work with chemicals Description of work: exposed to other Fetched water in past week Hours spent fetching water in past week Collected firewood in past week Hours spent collecting firewood in past week Household chores in past week:shopping Household chores in past week: cooking Household chores in past week: washing dishes or cleaning around the house Household chores in past week: washing clothes Household chores in past week: caring for children Household chores in past week: caring for old or sick Household chores in past week: other household tasks Number of hours engaged in past week  Age of child    HH6     HL4              ED5A     ED5B           melevel          fselevel        fsinsurance                  fsdisability  fshweight  fsweight ethnicity   HH7        zone
0             1.0               1.0          4.0                     YES                            YES                                1.0                            NaN                      NO                            NaN                                NaN                            NaN                                      NO                                    YES                                    YES                                                YES                          4.0                                       NO                                                 NO                                                                 YES                                                 NO                                                               NO                                                    NO                                                 NO                                      NO                         NO                                     NaN                              NO                                          NaN                                     NO                                     NO                                                YES                                                                    YES                                                 NO                                                 NO                                                    NO                                    3.0          10.0  URBAN    MALE           PRIMARY  GRADE 3           Primary  Junior secondary  Without insurance     Has functional difficulty   0.631502  0.631502      Igbo  ABIA  South East
1             1.0               2.0          2.0                     YES                             NO                                NaN                         ABROAD                      NO                            NaN                                NaN                            NaN                                      NO                                     NO                                     NO                                                 NO                          NaN                                      NaN                                                NaN                                                                 NaN                                                NaN                                                              NaN                                                   NaN                                                NaN                                     NaN                        YES                                     2.0                              NO                                          NaN                                    YES                                    YES                                                YES                                                                    YES                                                 NO                                                 NO                                                   YES                                    4.0          16.0  URBAN  FEMALE  SENIOR SECONDARY  GRADE 3  Senior secondary  Senior secondary  Without insurance  Has no functional difficulty   0.631502  0.631502      Igbo  ABIA  South East
2             1.0               3.0          3.0                     YES                            YES                                2.0                            NaN                     YES                            YES                                1.0                            NaN                                      NO                                     NO                                     NO                                                 NO                          NaN                                      NaN                                                NaN                                                                 NaN                                                NaN                                                              NaN                                                   NaN                                                NaN                                     NaN                         NO                                     NaN                              NO                                          NaN                                     NO                                     NO                                                YES                                                                     NO                                                 NO                                                 NO                                                    NO                                    0.0           5.0  URBAN    MALE   HIGHER/TERTIARY  GRADE 4   Higher/tertiary              None  Without insurance     Has functional difficulty   0.631502  0.631502      Igbo  ABIA  South East
3             1.0               5.0          5.0                     YES                            YES                                2.0                            NaN                     YES                            YES                                1.0                            NaN                                      NO                                    YES                                     NO                                                 NO                          3.0                                       NO                                                 NO                                                                  NO                                                 NO                                                               NO                                                    NO                                                 NO                                      NO                        YES                                    10.0                              NO                                          NaN                                     NO                                    YES                                                YES                                                                    YES                                                 NO                                                 NO                                                   YES                                    5.0          16.0  URBAN    MALE  SENIOR SECONDARY  GRADE 3  Senior secondary  Senior secondary  Without insurance  Has no functional difficulty   0.631502  0.631502      Igbo  ABIA  South East
4             1.0               6.0          5.0                     YES                            YES                                2.0                            NaN                     YES                            YES                                1.0                            NaN                                      NO                                    YES                                     NO                                                YES                          8.0                                       NO                                                 NO                                                                 YES                                                YES                                                               NO                                                    NO                                                 NO                                     YES                        YES                                     2.0                             YES                                          0.0                                    YES                                    YES                                                YES                                                                    YES                                                 NO                                                 NO                                                   YES                                    4.0          15.0  URBAN  FEMALE  SENIOR SECONDARY  GRADE 3  Senior secondary  Junior secondary  Without insurance  Has no functional difficulty   0.631502  0.631502      Igbo  ABIA  South East

In [ ]:
len(merger)

22706

In [ ]:
# Ensure full display without truncation
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.expand_frame_repr', False)  # Prevents wrapping
pd.set_option('display.large_repr', 'truncate')    # Prevents large output cutoff

In [ ]:
merger.head()

   Cluster number  Household number  Line number Is natural mother alive Does natural mother live in HH Natural mother's line number in HH Where does natural mother live Is natural father alive Does natural father live in HH Natural father's line number in HH Where does natural father live Worked or helped on garden in past week Helped in family business in past week Produced or sold articles in past week Engaged in any other activity for income in past week Hours worked in past week Activities required carrying heavy loads Activities required working with dangerous tools or heavy machinery Description of work: exposed to dust, fumes or gas Description of work: exposed to extreme temperatures or humidity Description of work: exposed to loud noise or vibration Description of work: required to work at heights Description of work: required to work with chemicals Description of work: exposed to other Fetched water in past week Hours spent fetching water in past week Collected firewood in past week Hours spent collecting firewood in past week Household chores in past week:shopping Household chores in past week: cooking Household chores in past week: washing dishes or cleaning around the house Household chores in past week: washing clothes Household chores in past week: caring for children Household chores in past week: caring for old or sick Household chores in past week: other household tasks Number of hours engaged in past week  Age of child    HH6     HL4              ED5A     ED5B           melevel          fselevel        fsinsurance                  fsdisability  fshweight  fsweight ethnicity   HH7        zone
0             1.0               1.0          4.0                     YES                            YES                                1.0                            NaN                      NO                            NaN                                NaN                            NaN                                      NO                                    YES                                    YES                                                YES                          4.0                                       NO                                                 NO                                                                 YES                                                 NO                                                               NO                                                    NO                                                 NO                                      NO                         NO                                     NaN                              NO                                          NaN                                     NO                                     NO                                                YES                                                                    YES                                                 NO                                                 NO                                                    NO                                    3.0          10.0  URBAN    MALE           PRIMARY  GRADE 3           Primary  Junior secondary  Without insurance     Has functional difficulty   0.631502  0.631502      Igbo  ABIA  South East
1             1.0               2.0          2.0                     YES                             NO                                NaN                         ABROAD                      NO                            NaN                                NaN                            NaN                                      NO                                     NO                                     NO                                                 NO                          NaN                                      NaN                                                NaN                                                                 NaN                                                NaN                                                              NaN                                                   NaN                                                NaN                                     NaN                        YES                                     2.0                              NO                                          NaN                                    YES                                    YES                                                YES                                                                    YES                                                 NO                                                 NO                                                   YES                                    4.0          16.0  URBAN  FEMALE  SENIOR SECONDARY  GRADE 3  Senior secondary  Senior secondary  Without insurance  Has no functional difficulty   0.631502  0.631502      Igbo  ABIA  South East
2             1.0               3.0          3.0                     YES                            YES                                2.0                            NaN                     YES                            YES                                1.0                            NaN                                      NO                                     NO                                     NO                                                 NO                          NaN                                      NaN                                                NaN                                                                 NaN                                                NaN                                                              NaN                                                   NaN                                                NaN                                     NaN                         NO                                     NaN                              NO                                          NaN                                     NO                                     NO                                                YES                                                                     NO                                                 NO                                                 NO                                                    NO                                    0.0           5.0  URBAN    MALE   HIGHER/TERTIARY  GRADE 4   Higher/tertiary              None  Without insurance     Has functional difficulty   0.631502  0.631502      Igbo  ABIA  South East
3             1.0               5.0          5.0                     YES                            YES                                2.0                            NaN                     YES                            YES                                1.0                            NaN                                      NO                                    YES                                     NO                                                 NO                          3.0                                       NO                                                 NO                                                                  NO                                                 NO                                                               NO                                                    NO                                                 NO                                      NO                        YES                                    10.0                              NO                                          NaN                                     NO                                    YES                                                YES                                                                    YES                                                 NO                                                 NO                                                   YES                                    5.0          16.0  URBAN    MALE  SENIOR SECONDARY  GRADE 3  Senior secondary  Senior secondary  Without insurance  Has no functional difficulty   0.631502  0.631502      Igbo  ABIA  South East
4             1.0               6.0          5.0                     YES                            YES                                2.0                            NaN                     YES                            YES                                1.0                            NaN                                      NO                                    YES                                     NO                                                YES                          8.0                                       NO                                                 NO                                                                 YES                                                YES                                                               NO                                                    NO                                                 NO                                     YES                        YES                                     2.0                             YES                                          0.0                                    YES                                    YES                                                YES                                                                    YES                                                 NO                                                 NO                                                   YES                                    4.0          15.0  URBAN  FEMALE  SENIOR SECONDARY  GRADE 3  Senior secondary  Junior secondary  Without insurance  Has no functional difficulty   0.631502  0.631502      Igbo  ABIA  South East

In [ ]:
merger.isnull().sum()

Cluster number                                                                    0
Household number                                                                  0
Line number                                                                       0
Is natural mother alive                                                           0
Does natural mother live in HH                                                  952
Natural mother's line number in HH                                             4355
Where does natural mother live                                                19303
Is natural father alive                                                           0
Does natural father live in HH                                                 2038
Natural father's line number in HH                                             5975
Where does natural father live                                                18769
Worked or helped on garden in past week                                         252
Helped in family business in past week                                          252
Produced or sold articles in past week                                          252
Engaged in any other activity for income in past week                           252
Hours worked in past week                                                     10519
Activities required carrying heavy loads                                      10519
Activities required working with dangerous tools or heavy machinery           10519
Description of work: exposed to dust, fumes or gas                            10519
Description of work: exposed to extreme temperatures or humidity              10519
Description of work: exposed to loud noise or vibration                       10519
Description of work: required to work at heights                              10519
Description of work: required to work with chemicals                          10519
Description of work: exposed to other                                         10519
Fetched water in past week                                                      252
Hours spent fetching water in past week                                        8789
Collected firewood in past week                                                 252
Hours spent collecting firewood in past week                                  15946
Household chores in past week:shopping                                          252
Household chores in past week: cooking                                          252
Household chores in past week: washing dishes or cleaning around the house      252
Household chores in past week: washing clothes                                  252
Household chores in past week: caring for children                              252
Household chores in past week: caring for old or sick                           252
Household chores in past week: other household tasks                            252
Number of hours engaged in past week                                           2982
Age of child                                                                    252
HH6                                                                               0
HL4                                                                               0
ED5A                                                                           9133
ED5B                                                                           9160
melevel                                                                         207
fselevel                                                                        263
fsinsurance                                                                     263
fsdisability                                                                    263
fshweight                                                                         0
fsweight                                                                          0
ethnicity                                                                         0
HH7                                                                               0
zone                                                                              0
dtype: int64

In [ ]:
merger.dtypes

Cluster number                                                                 float64
Household number                                                               float64
Line number                                                                    float64
Is natural mother alive                                                       category
Does natural mother live in HH                                                category
Natural mother's line number in HH                                            category
Where does natural mother live                                                category
Is natural father alive                                                       category
Does natural father live in HH                                                category
Natural father's line number in HH                                            category
Where does natural father live                                                category
Worked or helped on garden in past week                                       category
Helped in family business in past week                                        category
Produced or sold articles in past week                                        category
Engaged in any other activity for income in past week                         category
Hours worked in past week                                                     category
Activities required carrying heavy loads                                      category
Activities required working with dangerous tools or heavy machinery           category
Description of work: exposed to dust, fumes or gas                            category
Description of work: exposed to extreme temperatures or humidity              category
Description of work: exposed to loud noise or vibration                       category
Description of work: required to work at heights                              category
Description of work: required to work with chemicals                          category
Description of work: exposed to other                                         category
Fetched water in past week                                                    category
Hours spent fetching water in past week                                       category
Collected firewood in past week                                               category
Hours spent collecting firewood in past week                                  category
Household chores in past week:shopping                                        category
Household chores in past week: cooking                                        category
Household chores in past week: washing dishes or cleaning around the house    category
Household chores in past week: washing clothes                                category
Household chores in past week: caring for children                            category
Household chores in past week: caring for old or sick                         category
Household chores in past week: other household tasks                          category
Number of hours engaged in past week                                          category
Age of child                                                                   float64
HH6                                                                           category
HL4                                                                           category
ED5A                                                                          category
ED5B                                                                          category
melevel                                                                       category
fselevel                                                                      category
fsinsurance                                                                   category
fsdisability                                                                  category
fshweight                                                                      float64
fsweight                                                                       float64
ethnicity                                                                     category
HH7                                                                           category
zone                                                                          category
dtype: object

In [ ]:
list(merger.columns)

['Cluster number',
 'Household number',
 'Line number',
 'Is natural mother alive',
 'Does natural mother live in HH',
 "Natural mother's line number in HH",
 'Where does natural mother live',
 'Is natural father alive',
 'Does natural father live in HH',
 "Natural father's line number in HH",
 'Where does natural father live',
 'Worked or helped on garden in past week',
 'Helped in family business in past week',
 'Produced or sold articles in past week',
 'Engaged in any other activity for income in past week',
 'Hours worked in past week',
 'Activities required carrying heavy loads',
 'Activities required working with dangerous tools or heavy machinery',
 'Description of work: exposed to dust, fumes or gas',
 'Description of work: exposed to extreme temperatures or humidity',
 'Description of work: exposed to loud noise or vibration',
 'Description of work: required to work at heights',
 'Description of work: required to work with chemicals',
 'Description of work: exposed to other',
 'Fetched water in past week',
 'Hours spent fetching water in past week',
 'Collected firewood in past week',
 'Hours spent collecting firewood in past week',
 'Household chores in past week:shopping',
 'Household chores in past week: cooking',
 'Household chores in past week: washing dishes or cleaning around the house',
 'Household chores in past week: washing clothes',
 'Household chores in past week: caring for children',
 'Household chores in past week: caring for old or sick',
 'Household chores in past week: other household tasks',
 'Number of hours engaged in past week',
 'Age of child',
 'HH6',
 'HL4',
 'ED5A',
 'ED5B',
 'melevel',
 'fselevel',
 'fsinsurance',
 'fsdisability',
 'fshweight',
 'fsweight',
 'ethnicity',
 'HH7',
 'zone']

In [ ]:
merger['Helped in family business in past week'].value_counts()

Helped in family business in past week
NO             16172
YES             6264
NO RESPONSE       18
Name: count, dtype: int64

In [ ]:
#recoding variables into 1 or 0
columns = ['Worked or helped on garden in past week',
 'Helped in family business in past week',
 'Produced or sold articles in past week',
 'Engaged in any other activity for income in past week',
 'Hours worked in past week',
 'Activities required carrying heavy loads',
 'Activities required working with dangerous tools or heavy machinery',
 'Description of work: exposed to dust, fumes or gas',
 'Description of work: exposed to extreme temperatures or humidity',
 'Description of work: exposed to loud noise or vibration',
 'Description of work: required to work at heights',
 'Description of work: required to work with chemicals',
 'Description of work: exposed to other',
 'Fetched water in past week',]

map = {'YES': 1,
        'NO': 0,
        'Yes': 1,
        'No': 0,
        'DK': 0,
        'NO RESPONSE': 0}

df = merger.replace(map)

<ipython-input-75-11d4469ece90>:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = merger.replace(map)
<ipython-input-75-11d4469ece90>:24: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df = merger.replace(map)

In [ ]:
df.head()

   Cluster number  Household number  Line number Is natural mother alive Does natural mother live in HH Natural mother's line number in HH Where does natural mother live Is natural father alive Does natural father live in HH Natural father's line number in HH Where does natural father live Worked or helped on garden in past week Helped in family business in past week Produced or sold articles in past week Engaged in any other activity for income in past week Hours worked in past week Activities required carrying heavy loads Activities required working with dangerous tools or heavy machinery Description of work: exposed to dust, fumes or gas Description of work: exposed to extreme temperatures or humidity Description of work: exposed to loud noise or vibration Description of work: required to work at heights Description of work: required to work with chemicals Description of work: exposed to other Fetched water in past week Hours spent fetching water in past week Collected firewood in past week Hours spent collecting firewood in past week Household chores in past week:shopping Household chores in past week: cooking Household chores in past week: washing dishes or cleaning around the house Household chores in past week: washing clothes Household chores in past week: caring for children Household chores in past week: caring for old or sick Household chores in past week: other household tasks Number of hours engaged in past week  Age of child    HH6     HL4              ED5A     ED5B           melevel          fselevel        fsinsurance                  fsdisability  fshweight  fsweight ethnicity   HH7        zone
0             1.0               1.0          4.0                       1                              1                                1.0                            NaN                       0                            NaN                                NaN                            NaN                                       0                                      1                                      1                                                  1                          4.0                                        0                                                  0                                                                   1                                                  0                                                                0                                                     0                                                  0                                       0                          0                                     NaN                               0                                          NaN                                      0                                      0                                                  1                                                                      1                                                  0                                                  0                                                     0                                    3.0          10.0  URBAN    MALE           PRIMARY  GRADE 3           Primary  Junior secondary  Without insurance     Has functional difficulty   0.631502  0.631502      Igbo  ABIA  South East
1             1.0               2.0          2.0                       1                              0                                NaN                         ABROAD                       0                            NaN                                NaN                            NaN                                       0                                      0                                      0                                                  0                          NaN                                      NaN                                                NaN                                                                 NaN                                                NaN                                                              NaN                                                   NaN                                                NaN                                     NaN                          1                                     2.0                               0                                          NaN                                      1                                      1                                                  1                                                                      1                                                  0                                                  0                                                     1                                    4.0          16.0  URBAN  FEMALE  SENIOR SECONDARY  GRADE 3  Senior secondary  Senior secondary  Without insurance  Has no functional difficulty   0.631502  0.631502      Igbo  ABIA  South East
2             1.0               3.0          3.0                       1                              1                                2.0                            NaN                       1                              1                                1.0                            NaN                                       0                                      0                                      0                                                  0                          NaN                                      NaN                                                NaN                                                                 NaN                                                NaN                                                              NaN                                                   NaN                                                NaN                                     NaN                          0                                     NaN                               0                                          NaN                                      0                                      0                                                  1                                                                      0                                                  0                                                  0                                                     0                                    0.0           5.0  URBAN    MALE   HIGHER/TERTIARY  GRADE 4   Higher/tertiary              None  Without insurance     Has functional difficulty   0.631502  0.631502      Igbo  ABIA  South East
3             1.0               5.0          5.0                       1                              1                                2.0                            NaN                       1                              1                                1.0                            NaN                                       0                                      1                                      0                                                  0                          3.0                                        0                                                  0                                                                   0                                                  0                                                                0                                                     0                                                  0                                       0                          1                                    10.0                               0                                          NaN                                      0                                      1                                                  1                                                                      1                                                  0                                                  0                                                     1                                    5.0          16.0  URBAN    MALE  SENIOR SECONDARY  GRADE 3  Senior secondary  Senior secondary  Without insurance  Has no functional difficulty   0.631502  0.631502      Igbo  ABIA  South East
4             1.0               6.0          5.0                       1                              1                                2.0                            NaN                       1                              1                                1.0                            NaN                                       0                                      1                                      0                                                  1                          8.0                                        0                                                  0                                                                   1                                                  1                                                                0                                                     0                                                  0                                       1                          1                                     2.0                               1                                          0.0                                      1                                      1                                                  1                                                                      1                                                  0                                                  0                                                     1                                    4.0          15.0  URBAN  FEMALE  SENIOR SECONDARY  GRADE 3  Senior secondary  Junior secondary  Without insurance  Has no functional difficulty   0.631502  0.631502      Igbo  ABIA  South East

In [ ]:
df['Where does natural father live'].value_counts()

Where does natural father live
IN ANOTHER HOUSEHOLD IN THE SAME STATE    2694
IN ANOTHER HOUSEHOLD IN ANOTHER STATE     1154
ABROAD                                      69
0                                           17
INSTITUTION IN THIS COUNTRY                  3
Name: count, dtype: int64

In [ ]:
map = {'IN ANOTHER HOUSEHOLD IN THE SAME STATE	': 1,
        'IN ANOTHER HOUSEHOLD IN ANOTHER STATE': 2,
        'ABROAD': 3,
        'INSTITUTION IN THIS COUNTRY': 4,
        }

df = df.replace(map)

<ipython-input-78-8db27494c371>:7: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df = df.replace(map)

In [ ]:
df['zone'].isnull().sum()

0

In [ ]:
df.columns

Index(['Cluster number', 'Household number', 'Line number',
       'Is natural mother alive', 'Does natural mother live in HH',
       'Natural mother's line number in HH', 'Where does natural mother live',
       'Is natural father alive', 'Does natural father live in HH',
       'Natural father's line number in HH', 'Where does natural father live',
       'Worked or helped on garden in past week',
       'Helped in family business in past week',
       'Produced or sold articles in past week',
       'Engaged in any other activity for income in past week',
       'Hours worked in past week', 'Activities required carrying heavy loads',
       'Activities required working with dangerous tools or heavy machinery',
       'Description of work: exposed to dust, fumes or gas',
       'Description of work: exposed to extreme temperatures or humidity',
       'Description of work: exposed to loud noise or vibration',
       'Description of work: required to work at heights',
       'Description of work: required to work with chemicals',
       'Description of work: exposed to other', 'Fetched water in past week',
       'Hours spent fetching water in past week',
       'Collected firewood in past week',
       'Hours spent collecting firewood in past week',
       'Household chores in past week:shopping',
       'Household chores in past week: cooking',
       'Household chores in past week: washing dishes or cleaning around the house',
       'Household chores in past week: washing clothes',
       'Household chores in past week: caring for children',
       'Household chores in past week: caring for old or sick',
       'Household chores in past week: other household tasks',
       'Number of hours engaged in past week', 'Age of child', 'HH6', 'HL4',
       'ED5A', 'ED5B', 'melevel', 'fselevel', 'fsinsurance', 'fsdisability',
       'fshweight', 'fsweight', 'ethnicity', 'HH7', 'zone'],
      dtype='object')

In [ ]:
columns = ['HH6', 'HL4',
       'ED5A', 'ED5B', 'melevel', 'fselevel', 'fsinsurance', 'fsdisability', 'zone']

map = {'RURAL': 0,
       'URBAN': 1,
       'MALE': 1,
       'FEMALE': 0,
       'VEI/IEI': 1,
       'ECCDE': 2,
       'JUNIOR SECONDARY': 4,
       'PRIMARY': 3,
       'SECONDARY TECHNICAL': 5,
       'SENIOR SECONDARY': 6,
       'HIGHER/TERTIARY': 7,
       'GRADE 1': 1,
       'GRADE 2': 2,
       'GRADE 3': 3,
       'GRADE 4': 4,
       'GRADE 5': 5,
       'GRADE 6': 6,
       'None': 0,
       'Primary': 1,
       'Junior secondary': 2,
       'Senior secondary': 3,
       'Higher/tertiary': 4,
       'Missing/DK':np.nan,
       'Without insurance': 0,
       'With insurance': 1,
       'Has no functional difficulty': 0,
       'Has functional difficulty': 1,
       'North West': 1,
       'North Central': 2,
       'North East': 3,
       'South South': 4,
       'South West': 5,
       'South East': 6
       }

for col in columns:
  df[col] = df[col].replace(map)

<ipython-input-88-4b61f8d829a6>:40: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].replace(map)
<ipython-input-88-4b61f8d829a6>:40: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df[col] = df[col].replace(map)

In [ ]:
df['zone'].value_counts()

zone
1    4875
2    4695
3    4275
4    3109
5    2956
6    2796
Name: count, dtype: int64

In [ ]:
df.head()

   Cluster number  Household number  Line number Is natural mother alive Does natural mother live in HH Natural mother's line number in HH Where does natural mother live Is natural father alive Does natural father live in HH Natural father's line number in HH Where does natural father live Worked or helped on garden in past week Helped in family business in past week Produced or sold articles in past week Engaged in any other activity for income in past week Hours worked in past week Activities required carrying heavy loads Activities required working with dangerous tools or heavy machinery Description of work: exposed to dust, fumes or gas Description of work: exposed to extreme temperatures or humidity Description of work: exposed to loud noise or vibration Description of work: required to work at heights Description of work: required to work with chemicals Description of work: exposed to other Fetched water in past week Hours spent fetching water in past week Collected firewood in past week Hours spent collecting firewood in past week Household chores in past week:shopping Household chores in past week: cooking Household chores in past week: washing dishes or cleaning around the house Household chores in past week: washing clothes Household chores in past week: caring for children Household chores in past week: caring for old or sick Household chores in past week: other household tasks Number of hours engaged in past week  Age of child HH6 HL4 ED5A ED5B melevel fselevel fsinsurance fsdisability  fshweight  fsweight ethnicity   HH7 zone
0             1.0               1.0          4.0                       1                              1                                1.0                            NaN                       0                            NaN                                NaN                            NaN                                       0                                      1                                      1                                                  1                          4.0                                        0                                                  0                                                                   1                                                  0                                                                0                                                     0                                                  0                                       0                          0                                     NaN                               0                                          NaN                                      0                                      0                                                  1                                                                      1                                                  0                                                  0                                                     0                                    3.0          10.0   1   1    3    3       1        2           0            1   0.631502  0.631502      Igbo  ABIA    6
1             1.0               2.0          2.0                       1                              0                                NaN                              3                       0                            NaN                                NaN                            NaN                                       0                                      0                                      0                                                  0                          NaN                                      NaN                                                NaN                                                                 NaN                                                NaN                                                              NaN                                                   NaN                                                NaN                                     NaN                          1                                     2.0                               0                                          NaN                                      1                                      1                                                  1                                                                      1                                                  0                                                  0                                                     1                                    4.0          16.0   1   0    6    3       3        3           0            0   0.631502  0.631502      Igbo  ABIA    6
2             1.0               3.0          3.0                       1                              1                                2.0                            NaN                       1                              1                                1.0                            NaN                                       0                                      0                                      0                                                  0                          NaN                                      NaN                                                NaN                                                                 NaN                                                NaN                                                              NaN                                                   NaN                                                NaN                                     NaN                          0                                     NaN                               0                                          NaN                                      0                                      0                                                  1                                                                      0                                                  0                                                  0                                                     0                                    0.0           5.0   1   1    7    4       4        0           0            1   0.631502  0.631502      Igbo  ABIA    6
3             1.0               5.0          5.0                       1                              1                                2.0                            NaN                       1                              1                                1.0                            NaN                                       0                                      1                                      0                                                  0                          3.0                                        0                                                  0                                                                   0                                                  0                                                                0                                                     0                                                  0                                       0                          1                                    10.0                               0                                          NaN                                      0                                      1                                                  1                                                                      1                                                  0                                                  0                                                     1                                    5.0          16.0   1   1    6    3       3        3           0            0   0.631502  0.631502      Igbo  ABIA    6
4             1.0               6.0          5.0                       1                              1                                2.0                            NaN                       1                              1                                1.0                            NaN                                       0                                      1                                      0                                                  1                          8.0                                        0                                                  0                                                                   1                                                  1                                                                0                                                     0                                                  0                                       1                          1                                     2.0                               1                                          0.0                                      1                                      1                                                  1                                                                      1                                                  0                                                  0                                                     1                                    4.0          15.0   1   0    6    3       3        2           0            0   0.631502  0.631502      Igbo  ABIA    6

In [ ]:
df.dtypes

Cluster number                                                                 float64
Household number                                                               float64
Line number                                                                    float64
Is natural mother alive                                                       category
Does natural mother live in HH                                                category
Natural mother's line number in HH                                            category
Where does natural mother live                                                category
Is natural father alive                                                       category
Does natural father live in HH                                                category
Natural father's line number in HH                                            category
Where does natural father live                                                category
Worked or helped on garden in past week                                       category
Helped in family business in past week                                        category
Produced or sold articles in past week                                        category
Engaged in any other activity for income in past week                         category
Hours worked in past week                                                     category
Activities required carrying heavy loads                                      category
Activities required working with dangerous tools or heavy machinery           category
Description of work: exposed to dust, fumes or gas                            category
Description of work: exposed to extreme temperatures or humidity              category
Description of work: exposed to loud noise or vibration                       category
Description of work: required to work at heights                              category
Description of work: required to work with chemicals                          category
Description of work: exposed to other                                         category
Fetched water in past week                                                    category
Hours spent fetching water in past week                                       category
Collected firewood in past week                                               category
Hours spent collecting firewood in past week                                  category
Household chores in past week:shopping                                        category
Household chores in past week: cooking                                        category
Household chores in past week: washing dishes or cleaning around the house    category
Household chores in past week: washing clothes                                category
Household chores in past week: caring for children                            category
Household chores in past week: caring for old or sick                         category
Household chores in past week: other household tasks                          category
Number of hours engaged in past week                                          category
Age of child                                                                   float64
HH6                                                                           category
HL4                                                                           category
ED5A                                                                          category
ED5B                                                                          category
melevel                                                                       category
fselevel                                                                      category
fsinsurance                                                                   category
fsdisability                                                                  category
fshweight                                                                      float64
fsweight                                                                       float64
ethnicity                                                                     category
HH7                                                                           category
zone                                                                          category
dtype: object

In [ ]:
dff = df.drop(columns = ['ethnicity', 'HH7'], axis = 1)

In [ ]:
dff.head()

   Cluster number  Household number  Line number Is natural mother alive Does natural mother live in HH Natural mother's line number in HH Where does natural mother live Is natural father alive Does natural father live in HH Natural father's line number in HH Where does natural father live Worked or helped on garden in past week Helped in family business in past week Produced or sold articles in past week Engaged in any other activity for income in past week Hours worked in past week Activities required carrying heavy loads Activities required working with dangerous tools or heavy machinery Description of work: exposed to dust, fumes or gas Description of work: exposed to extreme temperatures or humidity Description of work: exposed to loud noise or vibration Description of work: required to work at heights Description of work: required to work with chemicals Description of work: exposed to other Fetched water in past week Hours spent fetching water in past week Collected firewood in past week Hours spent collecting firewood in past week Household chores in past week:shopping Household chores in past week: cooking Household chores in past week: washing dishes or cleaning around the house Household chores in past week: washing clothes Household chores in past week: caring for children Household chores in past week: caring for old or sick Household chores in past week: other household tasks Number of hours engaged in past week  Age of child HH6 HL4 ED5A ED5B melevel fselevel fsinsurance fsdisability  fshweight  fsweight zone
0             1.0               1.0          4.0                       1                              1                                1.0                            NaN                       0                            NaN                                NaN                            NaN                                       0                                      1                                      1                                                  1                          4.0                                        0                                                  0                                                                   1                                                  0                                                                0                                                     0                                                  0                                       0                          0                                     NaN                               0                                          NaN                                      0                                      0                                                  1                                                                      1                                                  0                                                  0                                                     0                                    3.0          10.0   1   1    3    3       1        2           0            1   0.631502  0.631502    6
1             1.0               2.0          2.0                       1                              0                                NaN                              3                       0                            NaN                                NaN                            NaN                                       0                                      0                                      0                                                  0                          NaN                                      NaN                                                NaN                                                                 NaN                                                NaN                                                              NaN                                                   NaN                                                NaN                                     NaN                          1                                     2.0                               0                                          NaN                                      1                                      1                                                  1                                                                      1                                                  0                                                  0                                                     1                                    4.0          16.0   1   0    6    3       3        3           0            0   0.631502  0.631502    6
2             1.0               3.0          3.0                       1                              1                                2.0                            NaN                       1                              1                                1.0                            NaN                                       0                                      0                                      0                                                  0                          NaN                                      NaN                                                NaN                                                                 NaN                                                NaN                                                              NaN                                                   NaN                                                NaN                                     NaN                          0                                     NaN                               0                                          NaN                                      0                                      0                                                  1                                                                      0                                                  0                                                  0                                                     0                                    0.0           5.0   1   1    7    4       4        0           0            1   0.631502  0.631502    6
3             1.0               5.0          5.0                       1                              1                                2.0                            NaN                       1                              1                                1.0                            NaN                                       0                                      1                                      0                                                  0                          3.0                                        0                                                  0                                                                   0                                                  0                                                                0                                                     0                                                  0                                       0                          1                                    10.0                               0                                          NaN                                      0                                      1                                                  1                                                                      1                                                  0                                                  0                                                     1                                    5.0          16.0   1   1    6    3       3        3           0            0   0.631502  0.631502    6
4             1.0               6.0          5.0                       1                              1                                2.0                            NaN                       1                              1                                1.0                            NaN                                       0                                      1                                      0                                                  1                          8.0                                        0                                                  0                                                                   1                                                  1                                                                0                                                     0                                                  0                                       1                          1                                     2.0                               1                                          0.0                                      1                                      1                                                  1                                                                      1                                                  0                                                  0                                                     1                                    4.0          15.0   1   0    6    3       3        2           0            0   0.631502  0.631502    6

In [ ]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer
import numpy as np
import pandas as pd

# Custom function to clip negative values to a lower bound (e.g., 0)
def clip_negative_values(X):
    return np.clip(X, a_min=0, a_max=None)  # Ensure no negative values; keep other values unchanged

# Replace problematic string entries (e.g., 'Missing') with NaN
dff.replace(['', 'Missing'], np.nan, inplace=True)

# Separate binary and non-numeric columns that don't need imputation
#retain_columns = ['ethnicity', 'HH7', 'zone']
#binary_columns = df[retain_columns].copy()  # Copy to avoid modifying original df

# Select columns for imputation
#others_column = df.drop(columns=retain_columns)

# Ensure all columns are numeric
df1 = dff.apply(pd.to_numeric, errors='coerce')  # Convert non-numeric values to NaN

# Drop columns with all missing values
#df1 = df1.dropna(axis=1, how='all')

# Use HistGradientBoostingRegressor instead of the default BayesianRidge
imputer = IterativeImputer(estimator=HistGradientBoostingRegressor(), max_iter=10, random_state=0)

# Create a pipeline with imputation and clipping
pipeline = Pipeline([
    ('imputation', imputer),
    ('clip_negatives', FunctionTransformer(clip_negative_values, validate=False))
])

# Apply the pipeline to the numeric data
imputed_data = pipeline.fit_transform(df1)

# Convert the imputed result back to a DataFrame with correct column names
imputed_df = pd.DataFrame(imputed_data, columns=df1.columns)

# Combine the imputed continuous columns with the original binary columns
#final_df = pd.concat([imputed_df.reset_index(drop=True), binary_columns.reset_index(drop=True)], axis=1)

# Display the final DataFrame
print(imputed_df)

       Cluster number  Household number  Line number  Is natural mother alive  Does natural mother live in HH  Natural mother's line number in HH  Where does natural mother live  Is natural father alive  Does natural father live in HH  Natural father's line number in HH  Where does natural father live  Worked or helped on garden in past week  Helped in family business in past week  Produced or sold articles in past week  Engaged in any other activity for income in past week  Hours worked in past week  Activities required carrying heavy loads  Activities required working with dangerous tools or heavy machinery  Description of work: exposed to dust, fumes or gas  Description of work: exposed to extreme temperatures or humidity  Description of work: exposed to loud noise or vibration  Description of work: required to work at heights  Description of work: required to work with chemicals  Description of work: exposed to other  Fetched water in past week  Hours spent fetching water in past week  Collected firewood in past week  Hours spent collecting firewood in past week  Household chores in past week:shopping  Household chores in past week: cooking  Household chores in past week: washing dishes or cleaning around the house  Household chores in past week: washing clothes  Household chores in past week: caring for children  Household chores in past week: caring for old or sick  Household chores in past week: other household tasks  Number of hours engaged in past week  Age of child  HH6  HL4      ED5A      ED5B  melevel  fselevel  fsinsurance  fsdisability  fshweight  fsweight  zone
0                 1.0               1.0          4.0                      1.0                             1.0                            1.000000                        0.268292                      0.0                        0.006639                            1.672952                        1.146434                                      0.0                                     1.0                                     1.0                                                1.0                       4.000000                                  0.000000                                           0.000000                                                             1.000000                                            0.000000                                                          0.000000                                                0.000000                                           0.000000                                  0.000000                         0.0                                 1.682829                              0.0                                      0.649800                                     0.0                                     0.0                                                1.0                                                                      1.0                                                0.0                                                 0.0                                                    0.0                                 3.000000          10.0  1.0  1.0  3.000000  3.000000      1.0       2.0          0.0           1.0   0.631502  0.631502   6.0
1                 1.0               2.0          2.0                      1.0                             0.0                            0.925742                        3.000000                      0.0                        0.001056                            1.298249                        2.872088                                      0.0                                     0.0                                     0.0                                                0.0                       2.993479                                  0.062934                                           0.216816                                                             0.483990                                            0.085601                                                          0.016509                                                0.000000                                           0.166182                                  0.075708                         1.0                                 2.000000                              0.0                                      4.025223                                     1.0                                     1.0                                                1.0                                                                      1.0                                                0.0                                                 0.0                                                    1.0                                 4.000000          16.0  1.0  0.0  6.000000  3.000000      3.0       3.0          0.0           0.0   0.631502  0.631502   6.0
2                 1.0               3.0          3.0                      1.0                             1.0                            2.000000                        0.826710                      1.0                        1.000000                            1.000000                        1.148707                                      0.0                                     0.0                                     0.0                                                0.0                       1.172329                                  0.054082                                           0.442437                                                             0.111156                                            0.164948                                                          0.000000                                                0.126609                                           0.000000                                  0.174144                         0.0                                 0.105578                              0.0                                      0.359131                                     0.0                                     0.0                                                1.0                                                                      0.0                                                0.0                                                 0.0                                                    0.0                                 0.000000           5.0  1.0  1.0  7.000000  4.000000      4.0       0.0          0.0           1.0   0.631502  0.631502   6.0
3                 1.0               5.0          5.0                      1.0                             1.0                            2.000000                        0.241018                      1.0                        1.000000                            1.000000                        1.159547                                      0.0                                     1.0                                     0.0                                                0.0                       3.000000                                  0.000000                                           0.000000                                                             0.000000                                            0.000000                                                          0.000000                                                0.000000                                           0.000000                                  0.000000                         1.0                                10.000000                              0.0                                      3.054360                                     0.0                                     1.0                                                1.0                                                                      1.0                                                0.0                                                 0.0                                                    1.0                                 5.000000          16.0  1.0  1.0  6.000000  3.000000      3.0       3.0          0.0           0.0   0.631502  0.631502   6.0
4                 1.0               6.0          5.0                      1.0                             1.0                            2.000000                        0.276712                      1.0                        1.000000                            1.000000                        1.095884                                      0.0                                     1.0                                     0.0                                                1.0                       8.000000                                  0.000000                                           0.000000                                                             1.000000                                            1.000000                                                          0.000000                                                0.000000                                           0.000000                                  1.000000                         1.0                                 2.000000                              1.0                                      0.000000                                     1.0                                     1.0                                                1.0                                                                      1.0                                                0.0                                                 0.0                                                    1.0                                 4.000000          15.0  1.0  0.0  6.000000  3.000000      3.0       2.0          0.0           0.0   0.631502  0.631502   6.0
...               ...               ...          ...                      ...                             ...                                 ...                             ...                      ...                             ...                                 ...                             ...                                      ...                                     ...                                     ...                                                ...                            ...                                       ...                                                ...                                                                  ...                                                 ...                                                               ...                                                     ...                                                ...                                       ...                         ...                                      ...                              ...                                           ...                                     ...                                     ...                                                ...                                                                      ...                                                ...                                                 ...                                                    ...                                      ...           ...  ...  ...       ...       ...      ...       ...          ...           ...        ...       ...   ...
22701          1850.0              13.0          5.0                      1.0                             0.0                            1.982291                        2.000000                      1.0                        1.000000                            1.000000                        2.112127                                      0.0                                     0.0                                     0.0                                                0.0                       0.328240                                  0.165412                                           0.106275                                                             0.514571                                            0.747703                                                          0.266966                                                0.037611                                           0.351961                                  0.060279                         0.0                                 0.351965                              0.0                                      0.125933                                     0.0                                     0.0                                                0.0                                                                      0.0                                                0.0                                                 0.0                                                    0.0                                 0.317726           7.0  0.0  1.0  6.000000  3.000000      3.0       1.0          0.0           0.0   0.346335  0.346335   2.0
22702          1850.0              15.0          3.0                      1.0                             1.0                            2.000000                        1.965374                      1.0                        1.000000                            1.000000                        2.402963                                      0.0                                     0.0                                     0.0                                                0.0                       0.000000                                  0.140757                                           0.241079                                                             0.368677                                            0.553317                                                          0.295231                                                0.000000                                           0.110443                                  0.016225                         0.0                                 0.255655                              0.0                                      0.666278                                     0.0                                     0.0                                                0.0                                                                      0.0                                                0.0                                                 0.0                                                    0.0                                 0.596000           5.0  0.0  1.0  1.648219  5.933477      0.0       1.0          0.0           0.0   0.346335  0.346335   2.0
22703          1850.0              17.0         10.0                      1.0                             1.0                            2.000000                        0.329942                      1.0                        1.000000                            1.000000                        1.257800                                      0.0                                     0.0                                     0.0                                                0.0                       0.861594                                  0.232788                                           0.000000                                                             0.209182                                            0.182720                                                          0.962122                                                0.063877                                           0.007870                                  0.780511                         0.0                                 0.942494                              0.0                                      0.173815                                     0.0                                     0.0                                                0.0                                                                      0.0                                                0.0                                                 0.0                                                    0.0                                 0.436270           6.0  0.0  1.0  4.000000  3.000000      2.0       1.0          0.0           1.0   0.346335  1.731675   2.0
22704          1850.0              19.0          7.0                      1.0                             1.0                            2.000000                        0.342617                      1.0                        1.000000                            1.000000                        1.236621                                      0.0                                     0.0                                     0.0                                                0.0                       2.567904                                  0.234698                                           0.000000                                                             0.233244                                            0.000000                                                          0.995891                                                0.230983                                           0.026727                                  0.773100                         1.0                                 6.000000                              0.0                                      3.949525                                     0.0                                     0.0                                                1.0                                                                      1.0                                                0.0                                                 0.0                                                    0.0                                 5.000000          17.0  0.0  1.0  1.648219  5.637498      0.0       2.0          0.0           0.0   0.346335  0.346335   2.0
22705          1850.0              20.0          7.0                      1.0                             1.0                            2.000000                        0.392862                      1.0                        1.000000                            1.000000                        1.253852                                      0.0                                     0.0                                     0.0                                                0.0                       0.465691                                  0.197544                                           0.000000                                                             0.167679                                            0.169905                                                          0.958514                                                0.072894                                           0.007228                                  0.777619                         0.0                                 1.818735                              0.0                                      0.709276                                     0.0                                     0.0                                                0.0                                                                      0.0                                                0.0                                                 0.0                                                    0.0                                 1.253157           6.0  0.0  1.0  4.000000  3.000000      2.0       1.0          0.0           1.0   0.346335  1.385340   2.0

[22706 rows x 48 columns]

/usr/local/lib/python3.10/dist-packages/sklearn/impute/_iterative.py:895: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

In [ ]:
len(imputed_df)

22706

In [ ]:
df2 = df[['ethnicity', 'HH7']]
df2

             ethnicity   HH7
0                 Igbo  ABIA
1                 Igbo  ABIA
2                 Igbo  ABIA
3                 Igbo  ABIA
4                 Igbo  ABIA
...                ...   ...
22701  Other ethnicity   FCT
22702  Other ethnicity   FCT
22703  Other ethnicity   FCT
22704  Other ethnicity   FCT
22705  Other ethnicity   FCT

[22706 rows x 2 columns]

In [ ]:
df3 = pd.concat([imputed_df, df2], axis = 1)
df3.head()

   Cluster number  Household number  Line number  Is natural mother alive  Does natural mother live in HH  Natural mother's line number in HH  Where does natural mother live  Is natural father alive  Does natural father live in HH  Natural father's line number in HH  Where does natural father live  Worked or helped on garden in past week  Helped in family business in past week  Produced or sold articles in past week  Engaged in any other activity for income in past week  Hours worked in past week  Activities required carrying heavy loads  Activities required working with dangerous tools or heavy machinery  Description of work: exposed to dust, fumes or gas  Description of work: exposed to extreme temperatures or humidity  Description of work: exposed to loud noise or vibration  Description of work: required to work at heights  Description of work: required to work with chemicals  Description of work: exposed to other  Fetched water in past week  Hours spent fetching water in past week  Collected firewood in past week  Hours spent collecting firewood in past week  Household chores in past week:shopping  Household chores in past week: cooking  Household chores in past week: washing dishes or cleaning around the house  Household chores in past week: washing clothes  Household chores in past week: caring for children  Household chores in past week: caring for old or sick  Household chores in past week: other household tasks  Number of hours engaged in past week  Age of child  HH6  HL4  ED5A  ED5B  melevel  fselevel  fsinsurance  fsdisability  fshweight  fsweight  zone ethnicity   HH7
0             1.0               1.0          4.0                      1.0                             1.0                            1.000000                        0.268292                      0.0                        0.006639                            1.672952                        1.146434                                      0.0                                     1.0                                     1.0                                                1.0                       4.000000                                  0.000000                                           0.000000                                                             1.000000                                            0.000000                                                          0.000000                                                0.000000                                           0.000000                                  0.000000                         0.0                                 1.682829                              0.0                                      0.649800                                     0.0                                     0.0                                                1.0                                                                      1.0                                                0.0                                                 0.0                                                    0.0                                      3.0          10.0  1.0  1.0   3.0   3.0      1.0       2.0          0.0           1.0   0.631502  0.631502   6.0      Igbo  ABIA
1             1.0               2.0          2.0                      1.0                             0.0                            0.925742                        3.000000                      0.0                        0.001056                            1.298249                        2.872088                                      0.0                                     0.0                                     0.0                                                0.0                       2.993479                                  0.062934                                           0.216816                                                             0.483990                                            0.085601                                                          0.016509                                                0.000000                                           0.166182                                  0.075708                         1.0                                 2.000000                              0.0                                      4.025223                                     1.0                                     1.0                                                1.0                                                                      1.0                                                0.0                                                 0.0                                                    1.0                                      4.0          16.0  1.0  0.0   6.0   3.0      3.0       3.0          0.0           0.0   0.631502  0.631502   6.0      Igbo  ABIA
2             1.0               3.0          3.0                      1.0                             1.0                            2.000000                        0.826710                      1.0                        1.000000                            1.000000                        1.148707                                      0.0                                     0.0                                     0.0                                                0.0                       1.172329                                  0.054082                                           0.442437                                                             0.111156                                            0.164948                                                          0.000000                                                0.126609                                           0.000000                                  0.174144                         0.0                                 0.105578                              0.0                                      0.359131                                     0.0                                     0.0                                                1.0                                                                      0.0                                                0.0                                                 0.0                                                    0.0                                      0.0           5.0  1.0  1.0   7.0   4.0      4.0       0.0          0.0           1.0   0.631502  0.631502   6.0      Igbo  ABIA
3             1.0               5.0          5.0                      1.0                             1.0                            2.000000                        0.241018                      1.0                        1.000000                            1.000000                        1.159547                                      0.0                                     1.0                                     0.0                                                0.0                       3.000000                                  0.000000                                           0.000000                                                             0.000000                                            0.000000                                                          0.000000                                                0.000000                                           0.000000                                  0.000000                         1.0                                10.000000                              0.0                                      3.054360                                     0.0                                     1.0                                                1.0                                                                      1.0                                                0.0                                                 0.0                                                    1.0                                      5.0          16.0  1.0  1.0   6.0   3.0      3.0       3.0          0.0           0.0   0.631502  0.631502   6.0      Igbo  ABIA
4             1.0               6.0          5.0                      1.0                             1.0                            2.000000                        0.276712                      1.0                        1.000000                            1.000000                        1.095884                                      0.0                                     1.0                                     0.0                                                1.0                       8.000000                                  0.000000                                           0.000000                                                             1.000000                                            1.000000                                                          0.000000                                                0.000000                                           0.000000                                  1.000000                         1.0                                 2.000000                              1.0                                      0.000000                                     1.0                                     1.0                                                1.0                                                                      1.0                                                0.0                                                 0.0                                                    1.0                                      4.0          15.0  1.0  0.0   6.0   3.0      3.0       2.0          0.0           0.0   0.631502  0.631502   6.0      Igbo  ABIA

In [ ]:
len(final_df)

22706

In [ ]:
df = np.round(df3, 0)

In [ ]:
df.head()

   Cluster number  Household number  Line number  Is natural mother alive  Does natural mother live in HH  Natural mother's line number in HH  Where does natural mother live  Is natural father alive  Does natural father live in HH  Natural father's line number in HH  Where does natural father live  Worked or helped on garden in past week  Helped in family business in past week  Produced or sold articles in past week  Engaged in any other activity for income in past week  Hours worked in past week  Activities required carrying heavy loads  Activities required working with dangerous tools or heavy machinery  Description of work: exposed to dust, fumes or gas  Description of work: exposed to extreme temperatures or humidity  Description of work: exposed to loud noise or vibration  Description of work: required to work at heights  Description of work: required to work with chemicals  Description of work: exposed to other  Fetched water in past week  Hours spent fetching water in past week  Collected firewood in past week  Hours spent collecting firewood in past week  Household chores in past week:shopping  Household chores in past week: cooking  Household chores in past week: washing dishes or cleaning around the house  Household chores in past week: washing clothes  Household chores in past week: caring for children  Household chores in past week: caring for old or sick  Household chores in past week: other household tasks  Number of hours engaged in past week  Age of child  HH6  HL4  ED5A  ED5B  melevel  fselevel  fsinsurance  fsdisability  fshweight  fsweight  zone ethnicity   HH7
0             1.0               1.0          4.0                      1.0                             1.0                                 1.0                             0.0                      0.0                             0.0                                 2.0                             1.0                                      0.0                                     1.0                                     1.0                                                1.0                            4.0                                       0.0                                                0.0                                                                  1.0                                                 0.0                                                               0.0                                                     0.0                                                0.0                                       0.0                         0.0                                      2.0                              0.0                                           1.0                                     0.0                                     0.0                                                1.0                                                                      1.0                                                0.0                                                 0.0                                                    0.0                                      3.0          10.0  1.0  1.0   3.0   3.0      1.0       2.0          0.0           1.0        1.0       1.0   6.0      Igbo  ABIA
1             1.0               2.0          2.0                      1.0                             0.0                                 1.0                             3.0                      0.0                             0.0                                 1.0                             3.0                                      0.0                                     0.0                                     0.0                                                0.0                            3.0                                       0.0                                                0.0                                                                  0.0                                                 0.0                                                               0.0                                                     0.0                                                0.0                                       0.0                         1.0                                      2.0                              0.0                                           4.0                                     1.0                                     1.0                                                1.0                                                                      1.0                                                0.0                                                 0.0                                                    1.0                                      4.0          16.0  1.0  0.0   6.0   3.0      3.0       3.0          0.0           0.0        1.0       1.0   6.0      Igbo  ABIA
2             1.0               3.0          3.0                      1.0                             1.0                                 2.0                             1.0                      1.0                             1.0                                 1.0                             1.0                                      0.0                                     0.0                                     0.0                                                0.0                            1.0                                       0.0                                                0.0                                                                  0.0                                                 0.0                                                               0.0                                                     0.0                                                0.0                                       0.0                         0.0                                      0.0                              0.0                                           0.0                                     0.0                                     0.0                                                1.0                                                                      0.0                                                0.0                                                 0.0                                                    0.0                                      0.0           5.0  1.0  1.0   7.0   4.0      4.0       0.0          0.0           1.0        1.0       1.0   6.0      Igbo  ABIA
3             1.0               5.0          5.0                      1.0                             1.0                                 2.0                             0.0                      1.0                             1.0                                 1.0                             1.0                                      0.0                                     1.0                                     0.0                                                0.0                            3.0                                       0.0                                                0.0                                                                  0.0                                                 0.0                                                               0.0                                                     0.0                                                0.0                                       0.0                         1.0                                     10.0                              0.0                                           3.0                                     0.0                                     1.0                                                1.0                                                                      1.0                                                0.0                                                 0.0                                                    1.0                                      5.0          16.0  1.0  1.0   6.0   3.0      3.0       3.0          0.0           0.0        1.0       1.0   6.0      Igbo  ABIA
4             1.0               6.0          5.0                      1.0                             1.0                                 2.0                             0.0                      1.0                             1.0                                 1.0                             1.0                                      0.0                                     1.0                                     0.0                                                1.0                            8.0                                       0.0                                                0.0                                                                  1.0                                                 1.0                                                               0.0                                                     0.0                                                0.0                                       1.0                         1.0                                      2.0                              1.0                                           0.0                                     1.0                                     1.0                                                1.0                                                                      1.0                                                0.0                                                 0.0                                                    1.0                                      4.0          15.0  1.0  0.0   6.0   3.0      3.0       2.0          0.0           0.0        1.0       1.0   6.0      Igbo  ABIA

In [ ]:
df.isnull().sum()

Cluster number                                                                0
Household number                                                              0
Line number                                                                   0
Is natural mother alive                                                       0
Does natural mother live in HH                                                0
Natural mother's line number in HH                                            0
Where does natural mother live                                                0
Is natural father alive                                                       0
Does natural father live in HH                                                0
Natural father's line number in HH                                            0
Where does natural father live                                                0
Worked or helped on garden in past week                                       0
Helped in family business in past week                                        0
Produced or sold articles in past week                                        0
Engaged in any other activity for income in past week                         0
Hours worked in past week                                                     0
Activities required carrying heavy loads                                      0
Activities required working with dangerous tools or heavy machinery           0
Description of work: exposed to dust, fumes or gas                            0
Description of work: exposed to extreme temperatures or humidity              0
Description of work: exposed to loud noise or vibration                       0
Description of work: required to work at heights                              0
Description of work: required to work with chemicals                          0
Description of work: exposed to other                                         0
Fetched water in past week                                                    0
Hours spent fetching water in past week                                       0
Collected firewood in past week                                               0
Hours spent collecting firewood in past week                                  0
Household chores in past week:shopping                                        0
Household chores in past week: cooking                                        0
Household chores in past week: washing dishes or cleaning around the house    0
Household chores in past week: washing clothes                                0
Household chores in past week: caring for children                            0
Household chores in past week: caring for old or sick                         0
Household chores in past week: other household tasks                          0
Number of hours engaged in past week                                          0
Age of child                                                                  0
HH6                                                                           0
HL4                                                                           0
ED5A                                                                          0
ED5B                                                                          0
melevel                                                                       0
fselevel                                                                      0
fsinsurance                                                                   0
fsdisability                                                                  0
fshweight                                                                     0
fsweight                                                                      0
zone                                                                          0
ethnicity                                                                     0
HH7                                                                           0
dtype: int64

In [ ]:
# Define the bins and labels for age categories

bins = [4, 11, 14, 17]
labels = ['5-11 years', '12-14 years', '15-17 years']

# Categorize the age column
df['age_category'] = pd.cut(df['Age of child'], bins=bins, labels=labels, right=True)

# Display the updated DataFrame
print(df)

       Cluster number  Household number  Line number  Is natural mother alive  Does natural mother live in HH  Natural mother's line number in HH  Where does natural mother live  Is natural father alive  Does natural father live in HH  Natural father's line number in HH  Where does natural father live  Worked or helped on garden in past week  Helped in family business in past week  Produced or sold articles in past week  Engaged in any other activity for income in past week  Hours worked in past week  Activities required carrying heavy loads  Activities required working with dangerous tools or heavy machinery  Description of work: exposed to dust, fumes or gas  Description of work: exposed to extreme temperatures or humidity  Description of work: exposed to loud noise or vibration  Description of work: required to work at heights  Description of work: required to work with chemicals  Description of work: exposed to other  Fetched water in past week  Hours spent fetching water in past week  Collected firewood in past week  Hours spent collecting firewood in past week  Household chores in past week:shopping  Household chores in past week: cooking  Household chores in past week: washing dishes or cleaning around the house  Household chores in past week: washing clothes  Household chores in past week: caring for children  Household chores in past week: caring for old or sick  Household chores in past week: other household tasks  Number of hours engaged in past week  Age of child  HH6  HL4  ED5A  ED5B  melevel  fselevel  fsinsurance  fsdisability  fshweight  fsweight  zone        ethnicity   HH7 age_category
0                 1.0               1.0          4.0                      1.0                             1.0                                 1.0                             0.0                      0.0                             0.0                                 2.0                             1.0                                      0.0                                     1.0                                     1.0                                                1.0                            4.0                                       0.0                                                0.0                                                                  1.0                                                 0.0                                                               0.0                                                     0.0                                                0.0                                       0.0                         0.0                                      2.0                              0.0                                           1.0                                     0.0                                     0.0                                                1.0                                                                      1.0                                                0.0                                                 0.0                                                    0.0                                      3.0          10.0  1.0  1.0   3.0   3.0      1.0       2.0          0.0           1.0        1.0       1.0   6.0             Igbo  ABIA   5-11 years
1                 1.0               2.0          2.0                      1.0                             0.0                                 1.0                             3.0                      0.0                             0.0                                 1.0                             3.0                                      0.0                                     0.0                                     0.0                                                0.0                            3.0                                       0.0                                                0.0                                                                  0.0                                                 0.0                                                               0.0                                                     0.0                                                0.0                                       0.0                         1.0                                      2.0                              0.0                                           4.0                                     1.0                                     1.0                                                1.0                                                                      1.0                                                0.0                                                 0.0                                                    1.0                                      4.0          16.0  1.0  0.0   6.0   3.0      3.0       3.0          0.0           0.0        1.0       1.0   6.0             Igbo  ABIA  15-17 years
2                 1.0               3.0          3.0                      1.0                             1.0                                 2.0                             1.0                      1.0                             1.0                                 1.0                             1.0                                      0.0                                     0.0                                     0.0                                                0.0                            1.0                                       0.0                                                0.0                                                                  0.0                                                 0.0                                                               0.0                                                     0.0                                                0.0                                       0.0                         0.0                                      0.0                              0.0                                           0.0                                     0.0                                     0.0                                                1.0                                                                      0.0                                                0.0                                                 0.0                                                    0.0                                      0.0           5.0  1.0  1.0   7.0   4.0      4.0       0.0          0.0           1.0        1.0       1.0   6.0             Igbo  ABIA   5-11 years
3                 1.0               5.0          5.0                      1.0                             1.0                                 2.0                             0.0                      1.0                             1.0                                 1.0                             1.0                                      0.0                                     1.0                                     0.0                                                0.0                            3.0                                       0.0                                                0.0                                                                  0.0                                                 0.0                                                               0.0                                                     0.0                                                0.0                                       0.0                         1.0                                     10.0                              0.0                                           3.0                                     0.0                                     1.0                                                1.0                                                                      1.0                                                0.0                                                 0.0                                                    1.0                                      5.0          16.0  1.0  1.0   6.0   3.0      3.0       3.0          0.0           0.0        1.0       1.0   6.0             Igbo  ABIA  15-17 years
4                 1.0               6.0          5.0                      1.0                             1.0                                 2.0                             0.0                      1.0                             1.0                                 1.0                             1.0                                      0.0                                     1.0                                     0.0                                                1.0                            8.0                                       0.0                                                0.0                                                                  1.0                                                 1.0                                                               0.0                                                     0.0                                                0.0                                       1.0                         1.0                                      2.0                              1.0                                           0.0                                     1.0                                     1.0                                                1.0                                                                      1.0                                                0.0                                                 0.0                                                    1.0                                      4.0          15.0  1.0  0.0   6.0   3.0      3.0       2.0          0.0           0.0        1.0       1.0   6.0             Igbo  ABIA  15-17 years
...               ...               ...          ...                      ...                             ...                                 ...                             ...                      ...                             ...                                 ...                             ...                                      ...                                     ...                                     ...                                                ...                            ...                                       ...                                                ...                                                                  ...                                                 ...                                                               ...                                                     ...                                                ...                                       ...                         ...                                      ...                              ...                                           ...                                     ...                                     ...                                                ...                                                                      ...                                                ...                                                 ...                                                    ...                                      ...           ...  ...  ...   ...   ...      ...       ...          ...           ...        ...       ...   ...              ...   ...          ...
22701          1850.0              13.0          5.0                      1.0                             0.0                                 2.0                             2.0                      1.0                             1.0                                 1.0                             2.0                                      0.0                                     0.0                                     0.0                                                0.0                            0.0                                       0.0                                                0.0                                                                  1.0                                                 1.0                                                               0.0                                                     0.0                                                0.0                                       0.0                         0.0                                      0.0                              0.0                                           0.0                                     0.0                                     0.0                                                0.0                                                                      0.0                                                0.0                                                 0.0                                                    0.0                                      0.0           7.0  0.0  1.0   6.0   3.0      3.0       1.0          0.0           0.0        0.0       0.0   2.0  Other ethnicity   FCT   5-11 years
22702          1850.0              15.0          3.0                      1.0                             1.0                                 2.0                             2.0                      1.0                             1.0                                 1.0                             2.0                                      0.0                                     0.0                                     0.0                                                0.0                            0.0                                       0.0                                                0.0                                                                  0.0                                                 1.0                                                               0.0                                                     0.0                                                0.0                                       0.0                         0.0                                      0.0                              0.0                                           1.0                                     0.0                                     0.0                                                0.0                                                                      0.0                                                0.0                                                 0.0                                                    0.0                                      1.0           5.0  0.0  1.0   2.0   6.0      0.0       1.0          0.0           0.0        0.0       0.0   2.0  Other ethnicity   FCT   5-11 years
22703          1850.0              17.0         10.0                      1.0                             1.0                                 2.0                             0.0                      1.0                             1.0                                 1.0                             1.0                                      0.0                                     0.0                                     0.0                                                0.0                            1.0                                       0.0                                                0.0                                                                  0.0                                                 0.0                                                               1.0                                                     0.0                                                0.0                                       1.0                         0.0                                      1.0                              0.0                                           0.0                                     0.0                                     0.0                                                0.0                                                                      0.0                                                0.0                                                 0.0                                                    0.0                                      0.0           6.0  0.0  1.0   4.0   3.0      2.0       1.0          0.0           1.0        0.0       2.0   2.0  Other ethnicity   FCT   5-11 years
22704          1850.0              19.0          7.0                      1.0                             1.0                                 2.0                             0.0                      1.0                             1.0                                 1.0                             1.0                                      0.0                                     0.0                                     0.0                                                0.0                            3.0                                       0.0                                                0.0                                                                  0.0                                                 0.0                                                               1.0                                                     0.0                                                0.0                                       1.0                         1.0                                      6.0                              0.0                                           4.0                                     0.0                                     0.0                                                1.0                                                                      1.0                                                0.0                                                 0.0                                                    0.0                                      5.0          17.0  0.0  1.0   2.0   6.0      0.0       2.0          0.0           0.0        0.0       0.0   2.0  Other ethnicity   FCT  15-17 years
22705          1850.0              20.0          7.0                      1.0                             1.0                                 2.0                             0.0                      1.0                             1.0                                 1.0                             1.0                                      0.0                                     0.0                                     0.0                                                0.0                            0.0                                       0.0                                                0.0                                                                  0.0                                                 0.0                                                               1.0                                                     0.0                                                0.0                                       1.0                         0.0                                      2.0                              0.0                                           1.0                                     0.0                                     0.0                                                0.0                                                                      0.0                                                0.0                                                 0.0                                                    0.0                                      1.0           6.0  0.0  1.0   4.0   3.0      2.0       1.0          0.0           1.0        0.0       1.0   2.0  Other ethnicity   FCT   5-11 years

[22706 rows x 51 columns]

In [ ]:
df['age_category'].value_counts()

age_category
5-11 years     13677
12-14 years     4609
15-17 years     4420
Name: count, dtype: int64

In [ ]:
# Function to classify children based on age group and hours worked

def classify_on_track(row):
    age = row['Age of child']
    hours = row['Hours worked in past week']

    # Check age conditions and classify based on hours
    if 5 <= age <= 11:
        return 1 if hours >= 1 else 0
    elif 12 <= age <= 14:
        return 1 if hours >= 14 else 0
    elif 15 <= age <= 17:
        return 1 if hours >= 43 else 0
    else:
        return np.nan  # Return NaN for ages outside the specified range

In [ ]:
# Apply the classification to each row
df['Child_Labour_EA'] = df.apply(classify_on_track, axis=1)

In [ ]:
pd.crosstab(df['age_category'], df['Child_Labour_EA'])

Child_Labour_EA     0      1
age_category
5-11 years       1764  11913
12-14 years      3827    782
15-17 years      4362     58

In [ ]:
# Function to classify children based on age group and hours worked to identify child labour

def classify_on_track(row):
    age = row['Age of child']
    hours = row['Number of hours engaged in past week']

    # Classify child labour based on age-specific number of hours
    if 5 <= age <= 14:
        return 1 if hours >= 21 else 0  # 21 hours or more indicates child labour
    elif 15 <= age <= 17:
        return 1  # No limit on hours, any work indicates child labour
    else:
        return np.nan  # Return NaN for ages outside the specified range

In [ ]:
# Apply the classification to each row
df['Child_Labour_HC'] = df.apply(classify_on_track, axis=1)

In [ ]:
df['Child_Labour_HC'].value_counts()

Child_Labour_HC
0    17486
1     5220
Name: count, dtype: int64

In [ ]:
pd.crosstab(df['age_category'], df['Child_Labour_HC'])

Child_Labour_HC      0     1
age_category
5-11 years       13210   467
12-14 years       4276   333
15-17 years          0  4420

In [ ]:
df.head()

   Cluster number  Household number  Line number  Is natural mother alive  Does natural mother live in HH  Natural mother's line number in HH  Where does natural mother live  Is natural father alive  Does natural father live in HH  Natural father's line number in HH  Where does natural father live  Worked or helped on garden in past week  Helped in family business in past week  Produced or sold articles in past week  Engaged in any other activity for income in past week  Hours worked in past week  Activities required carrying heavy loads  Activities required working with dangerous tools or heavy machinery  Description of work: exposed to dust, fumes or gas  Description of work: exposed to extreme temperatures or humidity  Description of work: exposed to loud noise or vibration  Description of work: required to work at heights  Description of work: required to work with chemicals  Description of work: exposed to other  Fetched water in past week  Hours spent fetching water in past week  Collected firewood in past week  Hours spent collecting firewood in past week  Household chores in past week:shopping  Household chores in past week: cooking  Household chores in past week: washing dishes or cleaning around the house  Household chores in past week: washing clothes  Household chores in past week: caring for children  Household chores in past week: caring for old or sick  Household chores in past week: other household tasks  Number of hours engaged in past week  Age of child  HH6  HL4  ED5A  ED5B  melevel  fselevel  fsinsurance  fsdisability  fshweight  fsweight  zone ethnicity   HH7 age_category  Child_Labour_EA  Child_Labour_HC
0             1.0               1.0          4.0                      1.0                             1.0                                 1.0                             0.0                      0.0                             0.0                                 2.0                             1.0                                      0.0                                     1.0                                     1.0                                                1.0                            4.0                                       0.0                                                0.0                                                                  1.0                                                 0.0                                                               0.0                                                     0.0                                                0.0                                       0.0                         0.0                                      2.0                              0.0                                           1.0                                     0.0                                     0.0                                                1.0                                                                      1.0                                                0.0                                                 0.0                                                    0.0                                      3.0          10.0  1.0  1.0   3.0   3.0      1.0       2.0          0.0           1.0        1.0       1.0   6.0      Igbo  ABIA   5-11 years                1                0
1             1.0               2.0          2.0                      1.0                             0.0                                 1.0                             3.0                      0.0                             0.0                                 1.0                             3.0                                      0.0                                     0.0                                     0.0                                                0.0                            3.0                                       0.0                                                0.0                                                                  0.0                                                 0.0                                                               0.0                                                     0.0                                                0.0                                       0.0                         1.0                                      2.0                              0.0                                           4.0                                     1.0                                     1.0                                                1.0                                                                      1.0                                                0.0                                                 0.0                                                    1.0                                      4.0          16.0  1.0  0.0   6.0   3.0      3.0       3.0          0.0           0.0        1.0       1.0   6.0      Igbo  ABIA  15-17 years                0                1
2             1.0               3.0          3.0                      1.0                             1.0                                 2.0                             1.0                      1.0                             1.0                                 1.0                             1.0                                      0.0                                     0.0                                     0.0                                                0.0                            1.0                                       0.0                                                0.0                                                                  0.0                                                 0.0                                                               0.0                                                     0.0                                                0.0                                       0.0                         0.0                                      0.0                              0.0                                           0.0                                     0.0                                     0.0                                                1.0                                                                      0.0                                                0.0                                                 0.0                                                    0.0                                      0.0           5.0  1.0  1.0   7.0   4.0      4.0       0.0          0.0           1.0        1.0       1.0   6.0      Igbo  ABIA   5-11 years                1                0
3             1.0               5.0          5.0                      1.0                             1.0                                 2.0                             0.0                      1.0                             1.0                                 1.0                             1.0                                      0.0                                     1.0                                     0.0                                                0.0                            3.0                                       0.0                                                0.0                                                                  0.0                                                 0.0                                                               0.0                                                     0.0                                                0.0                                       0.0                         1.0                                     10.0                              0.0                                           3.0                                     0.0                                     1.0                                                1.0                                                                      1.0                                                0.0                                                 0.0                                                    1.0                                      5.0          16.0  1.0  1.0   6.0   3.0      3.0       3.0          0.0           0.0        1.0       1.0   6.0      Igbo  ABIA  15-17 years                0                1
4             1.0               6.0          5.0                      1.0                             1.0                                 2.0                             0.0                      1.0                             1.0                                 1.0                             1.0                                      0.0                                     1.0                                     0.0                                                1.0                            8.0                                       0.0                                                0.0                                                                  1.0                                                 1.0                                                               0.0                                                     0.0                                                0.0                                       1.0                         1.0                                      2.0                              1.0                                           0.0                                     1.0                                     1.0                                                1.0                                                                      1.0                                                0.0                                                 0.0                                                    1.0                                      4.0          15.0  1.0  0.0   6.0   3.0      3.0       2.0          0.0           0.0        1.0       1.0   6.0      Igbo  ABIA  15-17 years                0                1

In [ ]:
df.isnull().sum()

Cluster number                                                                0
Household number                                                              0
Line number                                                                   0
Is natural mother alive                                                       0
Does natural mother live in HH                                                0
Natural mother's line number in HH                                            0
Where does natural mother live                                                0
Is natural father alive                                                       0
Does natural father live in HH                                                0
Natural father's line number in HH                                            0
Where does natural father live                                                0
Worked or helped on garden in past week                                       0
Helped in family business in past week                                        0
Produced or sold articles in past week                                        0
Engaged in any other activity for income in past week                         0
Hours worked in past week                                                     0
Activities required carrying heavy loads                                      0
Activities required working with dangerous tools or heavy machinery           0
Description of work: exposed to dust, fumes or gas                            0
Description of work: exposed to extreme temperatures or humidity              0
Description of work: exposed to loud noise or vibration                       0
Description of work: required to work at heights                              0
Description of work: required to work with chemicals                          0
Description of work: exposed to other                                         0
Fetched water in past week                                                    0
Hours spent fetching water in past week                                       0
Collected firewood in past week                                               0
Hours spent collecting firewood in past week                                  0
Household chores in past week:shopping                                        0
Household chores in past week: cooking                                        0
Household chores in past week: washing dishes or cleaning around the house    0
Household chores in past week: washing clothes                                0
Household chores in past week: caring for children                            0
Household chores in past week: caring for old or sick                         0
Household chores in past week: other household tasks                          0
Number of hours engaged in past week                                          0
Age of child                                                                  0
HH6                                                                           0
HL4                                                                           0
ED5A                                                                          0
ED5B                                                                          0
melevel                                                                       0
fselevel                                                                      0
fsinsurance                                                                   0
fsdisability                                                                  0
fshweight                                                                     0
fsweight                                                                      0
zone                                                                          0
ethnicity                                                                     0
HH7                                                                           0
age_category                                                                  0
Child_Labour_EA                                                               0
Child_Labour_HC                                                               0
dtype: int64

In [ ]:
def classify_on_track(row):
    age = row['Age of child']
    water_hours = row.get('Hours spent fetching water in past week', 0)
    firewood_hours = row.get('Hours spent collecting firewood in past week', 0)
    other_hours = row.get('Number of hours engaged in past week', 0)

    # Aggregate total hours spent on household chores
    total_hours = water_hours + firewood_hours + other_hours

    # Classify child labour based on age and total hours
    if 5 <= age <= 14:
        return 1 if total_hours >= 21 else 0  # 21 hours or more indicates child labour
    elif 15 <= age <= 17:
        return 1  # No limit on hours, any engagement indicates child labour
    else:
        return np.nan  # Return NaN for ages outside the specified range

In [ ]:
# Apply the classification to each row
df['Child_Labour_HC1'] = df.apply(classify_on_track, axis=1)

In [ ]:
pd.crosstab(df['age_category'], df['Child_Labour_HC1'])

Child_Labour_HC1      0     1
age_category
5-11 years        11415  2262
12-14 years        3330  1279
15-17 years           0  4420

In [ ]:
from google.colab import files

# Save the DataFrame as a Stata file

df.to_stata('df.dta')  # Save as Stata .dta format

# Download the Stata file
files.download('df.dta')  # Download the Stata file

<ipython-input-122-7596d7dec08e>:5: InvalidColumnName:
Not all pandas column names were valid Stata variable names.
The following replacements have been made:

    Cluster number   ->   Cluster_number
    Household number   ->   Household_number
    Line number   ->   Line_number
    Is natural mother alive   ->   Is_natural_mother_alive
    Does natural mother live in HH   ->   Does_natural_mother_live_in_HH
    Natural mother's line number in HH   ->   Natural_mother_s_line_number_in_
    Where does natural mother live   ->   Where_does_natural_mother_live
    Is natural father alive   ->   Is_natural_father_alive
    Does natural father live in HH   ->   Does_natural_father_live_in_HH
    Natural father's line number in HH   ->   Natural_father_s_line_number_in_
    Where does natural father live   ->   Where_does_natural_father_live
    Worked or helped on garden in past week   ->   Worked_or_helped_on_garden_in_pa
    Helped in family business in past week   ->   Helped_in_family_business_in_pas
    Produced or sold articles in past week   ->   Produced_or_sold_articles_in_pas
    Engaged in any other activity for income in past week   ->   Engaged_in_any_other_activity_fo
    Hours worked in past week   ->   Hours_worked_in_past_week
    Activities required carrying heavy loads   ->   Activities_required_carrying_hea
    Activities required working with dangerous tools or heavy machinery   ->   Activities_required_working_with
    Description of work: exposed to dust, fumes or gas   ->   Description_of_work__exposed_to_
    Description of work: exposed to extreme temperatures or humidity   ->   _0Description_of_work__exposed_t
    Description of work: exposed to loud noise or vibration   ->   _1Description_of_work__exposed_t
    Description of work: required to work at heights   ->   Description_of_work__required_to
    Description of work: required to work with chemicals   ->   _2Description_of_work__required_
    Description of work: exposed to other   ->   _3Description_of_work__exposed_t
    Fetched water in past week   ->   Fetched_water_in_past_week
    Hours spent fetching water in past week   ->   Hours_spent_fetching_water_in_pa
    Collected firewood in past week   ->   Collected_firewood_in_past_week
    Hours spent collecting firewood in past week   ->   Hours_spent_collecting_firewood_
    Household chores in past week:shopping   ->   Household_chores_in_past_week_sh
    Household chores in past week: cooking   ->   Household_chores_in_past_week__c
    Household chores in past week: washing dishes or cleaning around the house   ->   Household_chores_in_past_week__w
    Household chores in past week: washing clothes   ->   _4Household_chores_in_past_week_
    Household chores in past week: caring for children   ->   _5Household_chores_in_past_week_
    Household chores in past week: caring for old or sick   ->   _6Household_chores_in_past_week_
    Household chores in past week: other household tasks   ->   Household_chores_in_past_week__o
    Number of hours engaged in past week   ->   Number_of_hours_engaged_in_past_
    Age of child   ->   Age_of_child

If this is not what you expect, please make sure you have Stata-compliant
column names in your DataFrame (strings only, max 32 characters, only
alphanumerics and underscores, no Stata reserved words)

  df.to_stata('df.dta')  # Save as Stata .dta format

In [ ]:
df.dtypes

Cluster number                                                                 float64
Household number                                                               float64
Line number                                                                    float64
Is natural mother alive                                                        float64
Does natural mother live in HH                                                 float64
Natural mother's line number in HH                                             float64
Where does natural mother live                                                 float64
Is natural father alive                                                        float64
Does natural father live in HH                                                 float64
Natural father's line number in HH                                             float64
Where does natural father live                                                 float64
Worked or helped on garden in past week                                        float64
Helped in family business in past week                                         float64
Produced or sold articles in past week                                         float64
Engaged in any other activity for income in past week                          float64
Hours worked in past week                                                      float64
Activities required carrying heavy loads                                       float64
Activities required working with dangerous tools or heavy machinery            float64
Description of work: exposed to dust, fumes or gas                             float64
Description of work: exposed to extreme temperatures or humidity               float64
Description of work: exposed to loud noise or vibration                        float64
Description of work: required to work at heights                               float64
Description of work: required to work with chemicals                           float64
Description of work: exposed to other                                          float64
Fetched water in past week                                                     float64
Hours spent fetching water in past week                                        float64
Collected firewood in past week                                                float64
Hours spent collecting firewood in past week                                   float64
Household chores in past week:shopping                                         float64
Household chores in past week: cooking                                         float64
Household chores in past week: washing dishes or cleaning around the house     float64
Household chores in past week: washing clothes                                 float64
Household chores in past week: caring for children                             float64
Household chores in past week: caring for old or sick                          float64
Household chores in past week: other household tasks                           float64
Number of hours engaged in past week                                           float64
Age of child                                                                   float64
HH6                                                                            float64
HL4                                                                            float64
ED5A                                                                           float64
ED5B                                                                           float64
melevel                                                                        float64
fselevel                                                                       float64
fsinsurance                                                                    float64
fsdisability                                                                   float64
fshweight                                                                      float64
fsweight                                                                       float64
zone                                                                           float64
ethnicity                                                                     category
HH7                                                                           category
age_category                                                                  category
Child_Labour_EA                                                                  int64
Child_Labour_HC                                                                  int64
Child_Labour_HC1                                                                 int64
dtype: object

In [ ]:
# Function to convert specified columns to category dtype
def convert_to_category(df, columns):
    for col in columns:
        df[col] = df[col].astype('category')

In [ ]:
df.columns

Index(['Cluster number', 'Household number', 'Line number',
       'Is natural mother alive', 'Does natural mother live in HH',
       'Natural mother's line number in HH', 'Where does natural mother live',
       'Is natural father alive', 'Does natural father live in HH',
       'Natural father's line number in HH', 'Where does natural father live',
       'Worked or helped on garden in past week',
       'Helped in family business in past week',
       'Produced or sold articles in past week',
       'Engaged in any other activity for income in past week',
       'Hours worked in past week', 'Activities required carrying heavy loads',
       'Activities required working with dangerous tools or heavy machinery',
       'Description of work: exposed to dust, fumes or gas',
       'Description of work: exposed to extreme temperatures or humidity',
       'Description of work: exposed to loud noise or vibration',
       'Description of work: required to work at heights',
       'Description of work: required to work with chemicals',
       'Description of work: exposed to other', 'Fetched water in past week',
       'Hours spent fetching water in past week',
       'Collected firewood in past week',
       'Hours spent collecting firewood in past week',
       'Household chores in past week:shopping',
       'Household chores in past week: cooking',
       'Household chores in past week: washing dishes or cleaning around the house',
       'Household chores in past week: washing clothes',
       'Household chores in past week: caring for children',
       'Household chores in past week: caring for old or sick',
       'Household chores in past week: other household tasks',
       'Number of hours engaged in past week', 'Age of child', 'HH6', 'HL4',
       'ED5A', 'ED5B', 'melevel', 'fselevel', 'fsinsurance', 'fsdisability',
       'fshweight', 'fsweight', 'zone', 'ethnicity', 'HH7', 'age_category',
       'Child_Labour_EA', 'Child_Labour_HC', 'Child_Labour_HC1'],
      dtype='object')

In [ ]:
columns = ['Is natural mother alive', 'Does natural mother live in HH',
       'Natural mother\'s line number in HH', 'Where does natural mother live',
       'Is natural father alive', 'Does natural father live in HH',
       'Natural father\'s line number in HH', 'Where does natural father live','Worked or helped on garden in past week',
       'Helped in family business in past week',
       'Produced or sold articles in past week',
       'Engaged in any other activity for income in past week',
       'Hours worked in past week', 'Activities required carrying heavy loads',
       'Activities required working with dangerous tools or heavy machinery',
       'Description of work: exposed to dust, fumes or gas',
       'Description of work: exposed to extreme temperatures or humidity',
       'Description of work: exposed to loud noise or vibration',
       'Description of work: required to work at heights',
       'Description of work: required to work with chemicals',
       'Description of work: exposed to other', 'Fetched water in past week',
       'Hours spent fetching water in past week',
       'Collected firewood in past week',
       'Hours spent collecting firewood in past week',
       'Household chores in past week:shopping',
       'Household chores in past week: cooking',
       'Household chores in past week: washing dishes or cleaning around the house',
       'Household chores in past week: washing clothes',
       'Household chores in past week: caring for children',
       'Household chores in past week: caring for old or sick',
       'Household chores in past week: other household tasks',
       'Number of hours engaged in past week', 'Age of child', 'age_category',
       'Child_Labour_EA', 'Child_Labour_HC', 'Child_Labour_HC1']

convert_to_category(df, columns)

In [ ]:
df.dtypes

Cluster number                                                                 float64
Household number                                                               float64
Line number                                                                    float64
Is natural mother alive                                                       category
Does natural mother live in HH                                                category
Natural mother's line number in HH                                            category
Where does natural mother live                                                category
Is natural father alive                                                       category
Does natural father live in HH                                                category
Natural father's line number in HH                                            category
Where does natural father live                                                category
Worked or helped on garden in past week                                       category
Helped in family business in past week                                        category
Produced or sold articles in past week                                        category
Engaged in any other activity for income in past week                         category
Hours worked in past week                                                     category
Activities required carrying heavy loads                                      category
Activities required working with dangerous tools or heavy machinery           category
Description of work: exposed to dust, fumes or gas                            category
Description of work: exposed to extreme temperatures or humidity              category
Description of work: exposed to loud noise or vibration                       category
Description of work: required to work at heights                              category
Description of work: required to work with chemicals                          category
Description of work: exposed to other                                         category
Fetched water in past week                                                    category
Hours spent fetching water in past week                                       category
Collected firewood in past week                                               category
Hours spent collecting firewood in past week                                  category
Household chores in past week:shopping                                        category
Household chores in past week: cooking                                        category
Household chores in past week: washing dishes or cleaning around the house    category
Household chores in past week: washing clothes                                category
Household chores in past week: caring for children                            category
Household chores in past week: caring for old or sick                         category
Household chores in past week: other household tasks                          category
Number of hours engaged in past week                                          category
Age of child                                                                  category
HH6                                                                            float64
HL4                                                                            float64
ED5A                                                                           float64
ED5B                                                                           float64
melevel                                                                        float64
fselevel                                                                       float64
fsinsurance                                                                    float64
fsdisability                                                                   float64
fshweight                                                                      float64
fsweight                                                                       float64
zone                                                                           float64
ethnicity                                                                     category
HH7                                                                           category
age_category                                                                  category
Child_Labour_EA                                                               category
Child_Labour_HC                                                               category
Child_Labour_HC1                                                              category
dtype: object

In [ ]:
from google.colab import files

# Save the DataFrame as a Stata file

df.to_stata('df.dta')  # Save as Stata .dta format

# Download the Stata file
files.download('df.dta')  # Download the Stata file

<ipython-input-128-7596d7dec08e>:5: InvalidColumnName:
Not all pandas column names were valid Stata variable names.
The following replacements have been made:

    Cluster number   ->   Cluster_number
    Household number   ->   Household_number
    Line number   ->   Line_number
    Is natural mother alive   ->   Is_natural_mother_alive
    Does natural mother live in HH   ->   Does_natural_mother_live_in_HH
    Natural mother's line number in HH   ->   Natural_mother_s_line_number_in_
    Where does natural mother live   ->   Where_does_natural_mother_live
    Is natural father alive   ->   Is_natural_father_alive
    Does natural father live in HH   ->   Does_natural_father_live_in_HH
    Natural father's line number in HH   ->   Natural_father_s_line_number_in_
    Where does natural father live   ->   Where_does_natural_father_live
    Worked or helped on garden in past week   ->   Worked_or_helped_on_garden_in_pa
    Helped in family business in past week   ->   Helped_in_family_business_in_pas
    Produced or sold articles in past week   ->   Produced_or_sold_articles_in_pas
    Engaged in any other activity for income in past week   ->   Engaged_in_any_other_activity_fo
    Hours worked in past week   ->   Hours_worked_in_past_week
    Activities required carrying heavy loads   ->   Activities_required_carrying_hea
    Activities required working with dangerous tools or heavy machinery   ->   Activities_required_working_with
    Description of work: exposed to dust, fumes or gas   ->   Description_of_work__exposed_to_
    Description of work: exposed to extreme temperatures or humidity   ->   _0Description_of_work__exposed_t
    Description of work: exposed to loud noise or vibration   ->   _1Description_of_work__exposed_t
    Description of work: required to work at heights   ->   Description_of_work__required_to
    Description of work: required to work with chemicals   ->   _2Description_of_work__required_
    Description of work: exposed to other   ->   _3Description_of_work__exposed_t
    Fetched water in past week   ->   Fetched_water_in_past_week
    Hours spent fetching water in past week   ->   Hours_spent_fetching_water_in_pa
    Collected firewood in past week   ->   Collected_firewood_in_past_week
    Hours spent collecting firewood in past week   ->   Hours_spent_collecting_firewood_
    Household chores in past week:shopping   ->   Household_chores_in_past_week_sh
    Household chores in past week: cooking   ->   Household_chores_in_past_week__c
    Household chores in past week: washing dishes or cleaning around the house   ->   Household_chores_in_past_week__w
    Household chores in past week: washing clothes   ->   _4Household_chores_in_past_week_
    Household chores in past week: caring for children   ->   _5Household_chores_in_past_week_
    Household chores in past week: caring for old or sick   ->   _6Household_chores_in_past_week_
    Household chores in past week: other household tasks   ->   Household_chores_in_past_week__o
    Number of hours engaged in past week   ->   Number_of_hours_engaged_in_past_
    Age of child   ->   Age_of_child

If this is not what you expect, please make sure you have Stata-compliant
column names in your DataFrame (strings only, max 32 characters, only
alphanumerics and underscores, no Stata reserved words)

  df.to_stata('df.dta')  # Save as Stata .dta format
<ipython-input-128-7596d7dec08e>:5: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Is_natural_mother_alive contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata('df.dta')  # Save as Stata .dta format
<ipython-input-128-7596d7dec08e>:5: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Does_natural_mother_live_in_HH contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata('df.dta')  # Save as Stata .dta format
<ipython-input-128-7596d7dec08e>:5: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Natural_mother_s_line_number_in_ contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata('df.dta')  # Save as Stata .dta format
<ipython-input-128-7596d7dec08e>:5: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Where_does_natural_mother_live contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata('df.dta')  # Save as Stata .dta format
<ipython-input-128-7596d7dec08e>:5: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Is_natural_father_alive contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata('df.dta')  # Save as Stata .dta format
<ipython-input-128-7596d7dec08e>:5: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Does_natural_father_live_in_HH contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata('df.dta')  # Save as Stata .dta format
<ipython-input-128-7596d7dec08e>:5: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Natural_father_s_line_number_in_ contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata('df.dta')  # Save as Stata .dta format
<ipython-input-128-7596d7dec08e>:5: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Where_does_natural_father_live contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata('df.dta')  # Save as Stata .dta format
<ipython-input-128-7596d7dec08e>:5: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Worked_or_helped_on_garden_in_pa contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata('df.dta')  # Save as Stata .dta format
<ipython-input-128-7596d7dec08e>:5: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Helped_in_family_business_in_pas contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata('df.dta')  # Save as Stata .dta format
<ipython-input-128-7596d7dec08e>:5: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Produced_or_sold_articles_in_pas contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata('df.dta')  # Save as Stata .dta format
<ipython-input-128-7596d7dec08e>:5: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Engaged_in_any_other_activity_fo contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata('df.dta')  # Save as Stata .dta format
<ipython-input-128-7596d7dec08e>:5: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Hours_worked_in_past_week contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata('df.dta')  # Save as Stata .dta format
<ipython-input-128-7596d7dec08e>:5: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Activities_required_carrying_hea contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata('df.dta')  # Save as Stata .dta format
<ipython-input-128-7596d7dec08e>:5: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Activities_required_working_with contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata('df.dta')  # Save as Stata .dta format
<ipython-input-128-7596d7dec08e>:5: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Description_of_work__exposed_to_ contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata('df.dta')  # Save as Stata .dta format
<ipython-input-128-7596d7dec08e>:5: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column _0Description_of_work__exposed_t contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata('df.dta')  # Save as Stata .dta format
<ipython-input-128-7596d7dec08e>:5: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column _1Description_of_work__exposed_t contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata('df.dta')  # Save as Stata .dta format
<ipython-input-128-7596d7dec08e>:5: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Description_of_work__required_to contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata('df.dta')  # Save as Stata .dta format
<ipython-input-128-7596d7dec08e>:5: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column _2Description_of_work__required_ contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata('df.dta')  # Save as Stata .dta format
<ipython-input-128-7596d7dec08e>:5: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column _3Description_of_work__exposed_t contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata('df.dta')  # Save as Stata .dta format
<ipython-input-128-7596d7dec08e>:5: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Fetched_water_in_past_week contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata('df.dta')  # Save as Stata .dta format
<ipython-input-128-7596d7dec08e>:5: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Hours_spent_fetching_water_in_pa contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata('df.dta')  # Save as Stata .dta format
<ipython-input-128-7596d7dec08e>:5: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Collected_firewood_in_past_week contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata('df.dta')  # Save as Stata .dta format
<ipython-input-128-7596d7dec08e>:5: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Hours_spent_collecting_firewood_ contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata('df.dta')  # Save as Stata .dta format
<ipython-input-128-7596d7dec08e>:5: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Household_chores_in_past_week_sh contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata('df.dta')  # Save as Stata .dta format
<ipython-input-128-7596d7dec08e>:5: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Household_chores_in_past_week__c contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata('df.dta')  # Save as Stata .dta format
<ipython-input-128-7596d7dec08e>:5: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Household_chores_in_past_week__w contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata('df.dta')  # Save as Stata .dta format
<ipython-input-128-7596d7dec08e>:5: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column _4Household_chores_in_past_week_ contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata('df.dta')  # Save as Stata .dta format
<ipython-input-128-7596d7dec08e>:5: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column _5Household_chores_in_past_week_ contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata('df.dta')  # Save as Stata .dta format
<ipython-input-128-7596d7dec08e>:5: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column _6Household_chores_in_past_week_ contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata('df.dta')  # Save as Stata .dta format
<ipython-input-128-7596d7dec08e>:5: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Household_chores_in_past_week__o contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata('df.dta')  # Save as Stata .dta format
<ipython-input-128-7596d7dec08e>:5: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Number_of_hours_engaged_in_past_ contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata('df.dta')  # Save as Stata .dta format
<ipython-input-128-7596d7dec08e>:5: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Age_of_child contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata('df.dta')  # Save as Stata .dta format
<ipython-input-128-7596d7dec08e>:5: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Child_Labour_EA contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata('df.dta')  # Save as Stata .dta format
<ipython-input-128-7596d7dec08e>:5: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Child_Labour_HC contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata('df.dta')  # Save as Stata .dta format
<ipython-input-128-7596d7dec08e>:5: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Child_Labour_HC1 contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata('df.dta')  # Save as Stata .dta format

In [ ]:
# Function to export dataframe to Stata with value labels
def export_to_stata(df, file_name, value_labels):
    # Apply value labels to categorical columns
    for col, labels in value_labels.items():
        df[col] = df[col].cat.rename_categories(labels)

    # Export to Stata file
    df.to_stata(file_name, write_index=False)

In [ ]:
value_labels = {'Child_Labour_EA': {0: 'No Child Labour', 1: 'Child Labour'},
                'Child_Labour_HC': {0: 'No Child Labour', 1: 'Child Labour'}}

export_to_stata(df, 'output.dta', value_labels)

<ipython-input-129-ed836c5bbbd5>:8: InvalidColumnName:
Not all pandas column names were valid Stata variable names.
The following replacements have been made:

    Cluster number   ->   Cluster_number
    Household number   ->   Household_number
    Line number   ->   Line_number
    Is natural mother alive   ->   Is_natural_mother_alive
    Does natural mother live in HH   ->   Does_natural_mother_live_in_HH
    Natural mother's line number in HH   ->   Natural_mother_s_line_number_in_
    Where does natural mother live   ->   Where_does_natural_mother_live
    Is natural father alive   ->   Is_natural_father_alive
    Does natural father live in HH   ->   Does_natural_father_live_in_HH
    Natural father's line number in HH   ->   Natural_father_s_line_number_in_
    Where does natural father live   ->   Where_does_natural_father_live
    Worked or helped on garden in past week   ->   Worked_or_helped_on_garden_in_pa
    Helped in family business in past week   ->   Helped_in_family_business_in_pas
    Produced or sold articles in past week   ->   Produced_or_sold_articles_in_pas
    Engaged in any other activity for income in past week   ->   Engaged_in_any_other_activity_fo
    Hours worked in past week   ->   Hours_worked_in_past_week
    Activities required carrying heavy loads   ->   Activities_required_carrying_hea
    Activities required working with dangerous tools or heavy machinery   ->   Activities_required_working_with
    Description of work: exposed to dust, fumes or gas   ->   Description_of_work__exposed_to_
    Description of work: exposed to extreme temperatures or humidity   ->   _0Description_of_work__exposed_t
    Description of work: exposed to loud noise or vibration   ->   _1Description_of_work__exposed_t
    Description of work: required to work at heights   ->   Description_of_work__required_to
    Description of work: required to work with chemicals   ->   _2Description_of_work__required_
    Description of work: exposed to other   ->   _3Description_of_work__exposed_t
    Fetched water in past week   ->   Fetched_water_in_past_week
    Hours spent fetching water in past week   ->   Hours_spent_fetching_water_in_pa
    Collected firewood in past week   ->   Collected_firewood_in_past_week
    Hours spent collecting firewood in past week   ->   Hours_spent_collecting_firewood_
    Household chores in past week:shopping   ->   Household_chores_in_past_week_sh
    Household chores in past week: cooking   ->   Household_chores_in_past_week__c
    Household chores in past week: washing dishes or cleaning around the house   ->   Household_chores_in_past_week__w
    Household chores in past week: washing clothes   ->   _4Household_chores_in_past_week_
    Household chores in past week: caring for children   ->   _5Household_chores_in_past_week_
    Household chores in past week: caring for old or sick   ->   _6Household_chores_in_past_week_
    Household chores in past week: other household tasks   ->   Household_chores_in_past_week__o
    Number of hours engaged in past week   ->   Number_of_hours_engaged_in_past_
    Age of child   ->   Age_of_child

If this is not what you expect, please make sure you have Stata-compliant
column names in your DataFrame (strings only, max 32 characters, only
alphanumerics and underscores, no Stata reserved words)

  df.to_stata(file_name, write_index=False)
<ipython-input-129-ed836c5bbbd5>:8: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Is_natural_mother_alive contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata(file_name, write_index=False)
<ipython-input-129-ed836c5bbbd5>:8: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Does_natural_mother_live_in_HH contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata(file_name, write_index=False)
<ipython-input-129-ed836c5bbbd5>:8: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Natural_mother_s_line_number_in_ contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata(file_name, write_index=False)
<ipython-input-129-ed836c5bbbd5>:8: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Where_does_natural_mother_live contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata(file_name, write_index=False)
<ipython-input-129-ed836c5bbbd5>:8: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Is_natural_father_alive contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata(file_name, write_index=False)
<ipython-input-129-ed836c5bbbd5>:8: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Does_natural_father_live_in_HH contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata(file_name, write_index=False)
<ipython-input-129-ed836c5bbbd5>:8: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Natural_father_s_line_number_in_ contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata(file_name, write_index=False)
<ipython-input-129-ed836c5bbbd5>:8: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Where_does_natural_father_live contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata(file_name, write_index=False)
<ipython-input-129-ed836c5bbbd5>:8: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Worked_or_helped_on_garden_in_pa contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata(file_name, write_index=False)
<ipython-input-129-ed836c5bbbd5>:8: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Helped_in_family_business_in_pas contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata(file_name, write_index=False)
<ipython-input-129-ed836c5bbbd5>:8: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Produced_or_sold_articles_in_pas contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata(file_name, write_index=False)
<ipython-input-129-ed836c5bbbd5>:8: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Engaged_in_any_other_activity_fo contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata(file_name, write_index=False)
<ipython-input-129-ed836c5bbbd5>:8: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Hours_worked_in_past_week contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata(file_name, write_index=False)
<ipython-input-129-ed836c5bbbd5>:8: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Activities_required_carrying_hea contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata(file_name, write_index=False)
<ipython-input-129-ed836c5bbbd5>:8: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Activities_required_working_with contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata(file_name, write_index=False)
<ipython-input-129-ed836c5bbbd5>:8: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Description_of_work__exposed_to_ contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata(file_name, write_index=False)
<ipython-input-129-ed836c5bbbd5>:8: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column _0Description_of_work__exposed_t contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata(file_name, write_index=False)
<ipython-input-129-ed836c5bbbd5>:8: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column _1Description_of_work__exposed_t contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata(file_name, write_index=False)
<ipython-input-129-ed836c5bbbd5>:8: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Description_of_work__required_to contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata(file_name, write_index=False)
<ipython-input-129-ed836c5bbbd5>:8: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column _2Description_of_work__required_ contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata(file_name, write_index=False)
<ipython-input-129-ed836c5bbbd5>:8: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column _3Description_of_work__exposed_t contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata(file_name, write_index=False)
<ipython-input-129-ed836c5bbbd5>:8: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Fetched_water_in_past_week contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata(file_name, write_index=False)
<ipython-input-129-ed836c5bbbd5>:8: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Hours_spent_fetching_water_in_pa contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata(file_name, write_index=False)
<ipython-input-129-ed836c5bbbd5>:8: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Collected_firewood_in_past_week contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata(file_name, write_index=False)
<ipython-input-129-ed836c5bbbd5>:8: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Hours_spent_collecting_firewood_ contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata(file_name, write_index=False)
<ipython-input-129-ed836c5bbbd5>:8: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Household_chores_in_past_week_sh contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata(file_name, write_index=False)
<ipython-input-129-ed836c5bbbd5>:8: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Household_chores_in_past_week__c contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata(file_name, write_index=False)
<ipython-input-129-ed836c5bbbd5>:8: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Household_chores_in_past_week__w contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata(file_name, write_index=False)
<ipython-input-129-ed836c5bbbd5>:8: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column _4Household_chores_in_past_week_ contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata(file_name, write_index=False)
<ipython-input-129-ed836c5bbbd5>:8: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column _5Household_chores_in_past_week_ contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata(file_name, write_index=False)
<ipython-input-129-ed836c5bbbd5>:8: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column _6Household_chores_in_past_week_ contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata(file_name, write_index=False)
<ipython-input-129-ed836c5bbbd5>:8: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Household_chores_in_past_week__o contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata(file_name, write_index=False)
<ipython-input-129-ed836c5bbbd5>:8: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Number_of_hours_engaged_in_past_ contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata(file_name, write_index=False)
<ipython-input-129-ed836c5bbbd5>:8: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Age_of_child contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata(file_name, write_index=False)
<ipython-input-129-ed836c5bbbd5>:8: ValueLabelTypeMismatch:
Stata value labels (pandas categories) must be strings. Column Child_Labour_HC1 contains
non-string labels which will be converted to strings.  Please check that the
Stata data file created has not lost information due to duplicate labels.

  df.to_stata(file_name, write_index=False)

In [ ]:
# Download the Stata file
files.download('df.dta')  # Download the Stata file